#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

// whoopsies, no more free slots :)

#define ITEM_NONE 0

// Balls
#define ITEM_MASTER_BALL 1
#define ITEM_ULTRA_BALL 2
#define ITEM_GREAT_BALL 3
#define ITEM_POKE_BALL 4
#define ITEM_SAFARI_BALL 5
#define ITEM_NET_BALL 6
#define ITEM_DIVE_BALL 7
#define ITEM_NEST_BALL 8
#define ITEM_REPEAT_BALL 9
#define ITEM_TIMER_BALL 10
#define ITEM_LUXURY_BALL 11
#define ITEM_PREMIER_BALL 12
// Apricorn/New Balls
#define ITEM_LEVEL_BALL 13
#define ITEM_LURE_BALL 14
#define ITEM_MOON_BALL 15
#define ITEM_FRIEND_BALL 16
#define ITEM_LOVE_BALL 17
#define ITEM_HEAVY_BALL 18
#define ITEM_FAST_BALL 19
#define ITEM_SPORT_BALL 20
#define ITEM_HEAL_BALL 21
#define ITEM_QUICK_BALL 22
#define ITEM_DUSK_BALL 23
#define ITEM_CHERISH_BALL 24
#define ITEM_PARK_BALL 25
#define ITEM_DREAM_BALL 26
#define ITEM_BEAST_BALL 27

// Pokémon Items
#define ITEM_POTION 28
#define ITEM_ANTIDOTE 29
#define ITEM_BURN_HEAL 30
#define ITEM_ICE_HEAL 31
#define ITEM_AWAKENING 32
#define ITEM_PARALYZE_HEAL 33
#define ITEM_FULL_RESTORE 34
#define ITEM_MAX_POTION 35
#define ITEM_HYPER_POTION 36
#define ITEM_SUPER_POTION 37
#define ITEM_FULL_HEAL 38
#define ITEM_REVIVE 39
#define ITEM_MAX_REVIVE 40
#define ITEM_FRESH_WATER 41
#define ITEM_SODA_POP 42
#define ITEM_LEMONADE 43
#define ITEM_MOOMOO_MILK 44
#define ITEM_ENERGY_POWDER 45
#define ITEM_ENERGY_ROOT 46
#define ITEM_HEAL_POWDER 47
#define ITEM_REVIVAL_HERB 48
#define ITEM_ETHER 49
#define ITEM_MAX_ETHER 50
#define ITEM_ELIXIR 51
#define ITEM_MAX_ELIXIR 52
#define ITEM_LAVA_COOKIE 53
#define ITEM_BERRY_JUICE 59
#define ITEM_SACRED_ASH 60
#define ITEM_HP_UP 67
#define ITEM_PROTEIN 68
#define ITEM_IRON 69
#define ITEM_CARBOS 70
#define ITEM_CALCIUM 71
#define ITEM_RARE_CANDY 72
#define ITEM_PP_UP 73
#define ITEM_ZINC 74
#define ITEM_PP_MAX 75
#define ITEM_HEALTH_WING
#define ITEM_MUSCLE_WING
#define ITEM_RESIST_WING
#define ITEM_GENIUS_WING
#define ITEM_CLEVER_WING
#define ITEM_SWIFT_WING
#define ITEM_OLD_GATEAU
#define ITEM_GUARD_SPEC 76
#define ITEM_DIRE_HIT 77
#define ITEM_X_ATTACK 78
#define ITEM_X_DEFEND 79
#define ITEM_X_SPEED 80
#define ITEM_X_ACCURACY 81
#define ITEM_X_SPECIAL 82
#define ITEM_X_SP_DEF
#define ITEM_POKE_DOLL 83
#define ITEM_FLUFFY_TAIL 84
#define ITEM_BLUE_FLUTE 54
#define ITEM_YELLOW_FLUTE 55
#define ITEM_RED_FLUTE 56
#define ITEM_BLACK_FLUTE 57
#define ITEM_WHITE_FLUTE 58
#define ITEM_SHOAL_SALT 61
#define ITEM_SHOAL_SHELL 62
#define ITEM_RED_SHARD 63
#define ITEM_BLUE_SHARD 64
#define ITEM_YELLOW_SHARD 65
#define ITEM_GREEN_SHARD 66
#define ITEM_SUPER_REPEL 85
#define ITEM_MAX_REPEL 86
#define ITEM_ESCAPE_ROPE 87
#define ITEM_REPEL 88
#define ITEM_SUN_STONE 90
#define ITEM_MOON_STONE 91
#define ITEM_FIRE_STONE 92
#define ITEM_THUNDER_STONE 93
#define ITEM_WATER_STONE 94
#define ITEM_LEAF_STONE 96
#define ITEM_SHINY_STONE
#define ITEM_DUSK_STONE
#define ITEM_DAWN_STONE
#define ITEM_OVAL_STONE
#define ITEM_ICE_STONE
#define ITEM_CASTELIACONE
#define ITEM_ABILITY_CAPSULE
#define ITEM_LUMIOSE_GALETTE
#define ITEM_SHALOUR_SABLE
#define ITEM_BOTTLE_CAP
#define ITEM_BIG_MALASADA
#define ITEM_GOLD_BOTTLE_CAP
#define ITEM_ADRENALINE_ORB
#define ITEM_RED_NECTAR
#define ITEM_YELLOW_NECTAR
#define ITEM_PINK_NECTAR
#define ITEM_PURPLE_NECTAR

// mail
#define ITEM_ORANGE_MAIL 121
#define ITEM_HARBOR_MAIL 122
#define ITEM_GLITTER_MAIL 123
#define ITEM_MECH_MAIL 124
#define ITEM_WOOD_MAIL 125
#define ITEM_WAVE_MAIL 126
#define ITEM_BEAD_MAIL 127
#define ITEM_SHADOW_MAIL 128
#define ITEM_TROPIC_MAIL 129
#define ITEM_DREAM_MAIL 130
#define ITEM_FAB_MAIL 131
#define ITEM_RETRO_MAIL 132

// berries
#define ITEM_CHERI_BERRY 133
#define ITEM_CHESTO_BERRY 134
#define ITEM_PECHA_BERRY 135
#define ITEM_RAWST_BERRY 136
#define ITEM_ASPEAR_BERRY 137
#define ITEM_LEPPA_BERRY 138
#define ITEM_ORAN_BERRY 139
#define ITEM_PERSIM_BERRY 140
#define ITEM_LUM_BERRY 141
#define ITEM_SITRUS_BERRY 142
#define ITEM_FIGY_BERRY 143
#define ITEM_WIKI_BERRY 144
#define ITEM_MAGO_BERRY 145
#define ITEM_AGUAV_BERRY 146
#define ITEM_IAPAPA_BERRY 147
#define ITEM_RAZZ_BERRY 148
#define ITEM_BLUK_BERRY 149
#define ITEM_NANAB_BERRY 150
#define ITEM_WEPEAR_BERRY 151
#define ITEM_PINAP_BERRY 152
#define ITEM_POMEG_BERRY 153
#define ITEM_KELPSY_BERRY 154
#define ITEM_QUALOT_BERRY 155
#define ITEM_HONDEW_BERRY 156
#define ITEM_GREPA_BERRY 157
#define ITEM_TAMATO_BERRY 158
#define ITEM_CORNN_BERRY 159
#define ITEM_MAGOST_BERRY 160
#define ITEM_RABUTA_BERRY 161
#define ITEM_NOMEL_BERRY 162
#define ITEM_SPELON_BERRY 163
#define ITEM_PAMTRE_BERRY 164
#define ITEM_WATMEL_BERRY 165
#define ITEM_DURIN_BERRY 166
#define ITEM_BELUE_BERRY 167
#define ITEM_OCCA_BERRY
#define ITEM_PASSHO_BERRY
#define ITEM_WACAN_BERRY
#define ITEM_RINDO_BERRY
#define ITEM_YACHE_BERRY
#define ITEM_CHOPLE_BERRY
#define ITEM_KEBIA_BERRY
#define ITEM_SHUCA_BERRY
#define ITEM_COBA_BERRY
#define ITEM_PAYAPA_BERRY
#define ITEM_TANGA_BERRY
#define ITEM_CHARTI_BERRY
#define ITEM_KASIB_BERRY
#define ITEM_HABAN_BERRY
#define ITEM_COLBUR_BERRY
#define ITEM_BABIRI_BERRY
#define ITEM_CHILAN_BERRY
#define ITEM_ROSELI_BERRY
#define ITEM_LIECHI_BERRY 168
#define ITEM_GANLON_BERRY 169
#define ITEM_SALAC_BERRY 170
#define ITEM_PETAYA_BERRY 171
#define ITEM_APICOT_BERRY 172
#define ITEM_LANSAT_BERRY 173
#define ITEM_STARF_BERRY 174
#define ITEM_ENIGMA_BERRY 175
#define ITEM_MICLE_BERRY
#define ITEM_CUSTAP_BERRY
#define ITEM_JABOCA_BERRY
#define ITEM_ROWAP_BERRY
#define ITEM_KEE_BERRY
#define ITEM_MARANGA_BERRY

// mulch
#define ITEM_GROWTH_MULCH
#define ITEM_DAMP_MULCH
#define ITEM_STABLE_MULCH
#define ITEM_GOOEY_MULCH
#define ITEM_RICH_MULCH
#define ITEM_SURPRISE_MULCH
#define ITEM_BOOST_MULCH
#define ITEM_AMAZE_MULCH

// apricorns
#define ITEM_RED_APRICORN
#define ITEM_BLUE_APRICORN
#define ITEM_YELLOW_APRICORN
#define ITEM_GREEN_APRICORN
#define ITEM_PINK_APRICORN
#define ITEM_WHITE_APRICORN
#define ITEM_BLACK_APRICORN

// hold/misc. items
#define ITEM_BRIGHT_POWDER 179
#define ITEM_WHITE_HERB 180
#define ITEM_MACHO_BRACE 181
#define ITEM_EXP_SHARE 182
#define ITEM_QUICK_CLAW 183
#define ITEM_SOOTHE_BELL 184
#define ITEM_MENTAL_HERB 185
#define ITEM_CHOICE_BAND 186
#define ITEM_KINGS_ROCK 187
#define ITEM_SILVER_POWDER 188
#define ITEM_AMULET_COIN 189
#define ITEM_CLEANSE_TAG 190
#define ITEM_SOUL_DEW 191
#define ITEM_DEEP_SEA_TOOTH 192
#define ITEM_DEEP_SEA_SCALE 193
#define ITEM_SMOKE_BALL 194
#define ITEM_EVERSTONE 195
#define ITEM_FOCUS_BAND 196
#define ITEM_LUCKY_EGG 197
#define ITEM_SCOPE_LENS 198
#define ITEM_METAL_COAT 199
#define ITEM_LEFTOVERS 200
#define ITEM_DRAGON_SCALE 201
#define ITEM_LIGHT_BALL 202
#define ITEM_SOFT_SAND 203
#define ITEM_HARD_STONE 204
#define ITEM_MIRACLE_SEED 205
#define ITEM_BLACK_GLASSES 206
#define ITEM_BLACK_BELT 207
#define ITEM_MAGNET 208
#define ITEM_MYSTIC_WATER 209
#define ITEM_SHARP_BEAK 210
#define ITEM_POISON_BARB 211
#define ITEM_NEVER_MELT_ICE 212
#define ITEM_SPELL_TAG 213
#define ITEM_TWISTED_SPOON 214
#define ITEM_CHARCOAL 215
#define ITEM_DRAGON_FANG 216
#define ITEM_SILK_SCARF 217
#define ITEM_UP_GRADE 218
#define ITEM_SHELL_BELL 219
#define ITEM_SEA_INCENSE 220
#define ITEM_LAX_INCENSE 221
#define ITEM_LUCKY_PUNCH 222
#define ITEM_METAL_POWDER 223
#define ITEM_THICK_CLUB 224
#define ITEM_STICK 225
#define ITEM_RED_SCARF 254
#define ITEM_BLUE_SCARF 255
#define ITEM_PINK_SCARF 256
#define ITEM_GREEN_SCARF 257
#define ITEM_YELLOW_SCARF 258
#define ITEM_WIDE_LENS
#define ITEM_MUSCLE_BAND
#define ITEM_WISE_GLASSES
#define ITEM_EXPERT_BELT
#define ITEM_LIGHT_CLAY
#define ITEM_LIFE_ORB
#define ITEM_POWER_HERB
#define ITEM_TOXIC_ORB
#define ITEM_FLAME_ORB
#define ITEM_QUICK_POWDER
#define ITEM_FOCUS_SASH
#define ITEM_ZOOM_LENS
#define ITEM_METRONOME
#define ITEM_IRON_BALL
#define ITEM_LAGGING_TAIL
#define ITEM_DESTINY_KNOT
#define ITEM_BLACK_SLUDGE
#define ITEM_ICY_ROCK
#define ITEM_SMOOTH_ROCK
#define ITEM_HEAT_ROCK
#define ITEM_DAMP_ROCK
#define ITEM_GRIP_CLAW
#define ITEM_CHOICE_SCARF
#define ITEM_STICKY_BARB
#define ITEM_POWER_BRACER
#define ITEM_POWER_BELT
#define ITEM_POWER_LENS
#define ITEM_POWER_BAND
#define ITEM_POWER_ANKLET
#define ITEM_POWER_WEIGHT
#define ITEM_SHED_SHELL
#define ITEM_BIG_ROOT
#define ITEM_CHOICE_SPECS
#define ITEM_FLAME_PLATE
#define ITEM_SPLASH_PLATE
#define ITEM_ZAP_PLATE
#define ITEM_MEADOW_PLATE
#define ITEM_ICICLE_PLATE
#define ITEM_FIST_PLATE
#define ITEM_TOXIC_PLATE
#define ITEM_EARTH_PLATE
#define ITEM_SKY_PLATE
#define ITEM_MIND_PLATE
#define ITEM_INSECT_PLATE
#define ITEM_STONE_PLATE
#define ITEM_SPOOKY_PLATE
#define ITEM_DRACO_PLATE
#define ITEM_DREAD_PLATE
#define ITEM_IRON_PLATE
#define ITEM_PIXIE_PLATE
#define ITEM_ODD_INCENSE
#define ITEM_ROCK_INCENSE
#define ITEM_FULL_INCENSE
#define ITEM_WAVE_INCENSE
#define ITEM_ROSE_INCENSE
#define ITEM_LUCK_INCENSE
#define ITEM_PURE_INCENSE
#define ITEM_PROTECTOR
#define ITEM_ELECTIRIZER
#define ITEM_MAGMARIZER
#define ITEM_DUBIOUS_DISC
#define ITEM_REAPER_CLOTH
#define ITEM_RAZOR_CLAW
#define ITEM_RAZOR_FANG
#define ITEM_TINY_MUSHROOM 103
#define ITEM_BIG_MUSHROOM 104
#define ITEM_PEARL 106
#define ITEM_BIG_PEARL 107
#define ITEM_STARDUST 108
#define ITEM_STAR_PIECE 109
#define ITEM_NUGGET 110
#define ITEM_HEART_SCALE 111
#define ITEM_HONEY 89
#define ITEM_ROOT_FOSSIL 286
#define ITEM_CLAW_FOSSIL 287
#define ITEM_HELIX_FOSSIL
#define ITEM_DOME_FOSSIL
#define ITEM_OLD_AMBER
#define ITEM_ARMOR_FOSSIL
#define ITEM_SKULL_FOSSIL
#define ITEM_COVER_FOSSIL
#define ITEM_PLUME_FOSSIL
#define ITEM_JAW_FOSSIL
#define ITEM_SAIL_FOSSIL
#define ITEM_RARE_BONE
#define ITEM_ODD_KEYSTONE
#define ITEM_GRISEOUS_ORB
#define ITEM_DOUSE_DRIVE
#define ITEM_SHOCK_DRIVE
#define ITEM_BURN_DRIVE
#define ITEM_CHILL_DRIVE
#define ITEM_SWEET_HEART
#define ITEM_ADAMANT_ORB
#define ITEM_LUSTROUS_ORB
#define ITEM_PRISM_SCALE
#define ITEM_EVIOLITE
#define ITEM_FLOAT_STONE
#define ITEM_ROCKY_HELMET
#define ITEM_AIR_BALLOON
#define ITEM_RED_CARD
#define ITEM_RING_TARGET
#define ITEM_BINDING_BAND
#define ITEM_ABSORB_BULB
#define ITEM_CELL_BATTERY
#define ITEM_EJECT_BUTTON
#define ITEM_FIRE_GEM
#define ITEM_WATER_GEM
#define ITEM_ELECTRIC_GEM
#define ITEM_GRASS_GEM
#define ITEM_ICE_GEM
#define ITEM_FIGHTING_GEM
#define ITEM_POISON_GEM
#define ITEM_GROUND_GEM
#define ITEM_FLYING_GEM
#define ITEM_PSYCHIC_GEM
#define ITEM_BUG_GEM
#define ITEM_ROCK_GEM
#define ITEM_GHOST_GEM
#define ITEM_DRAGON_GEM
#define ITEM_DARK_GEM
#define ITEM_STEEL_GEM
#define ITEM_NORMAL_GEM
#define ITEM_FAIRY_GEM
#define ITEM_PRETTY_WING
#define ITEM_PASS_ORB
#define ITEM_POKE_TOY
#define ITEM_BALM_MUSHROOM
#define ITEM_BIG_NUGGET
#define ITEM_PEARL_STRING
#define ITEM_COMET_SHARD
#define ITEM_RELIC_COPPER
#define ITEM_RELIC_SILVER
#define ITEM_RELIC_GOLD
#define ITEM_RELIC_VASE
#define ITEM_RELIC_BAND
#define ITEM_RELIC_STATUE
#define ITEM_RELIC_CROWN
#define ITEM_DIRE_HIT_2
#define ITEM_X_ACCURACY_2
#define ITEM_X_ATTACK_2
#define ITEM_X_DEFEND_2
#define ITEM_X_SPECIAL_2
#define ITEM_X_SP_DEF_2
#define ITEM_X_SPEED_2
#define ITEM_DIRE_HIT_3
#define ITEM_X_ACCURACY_3
#define ITEM_X_ATTACK_3
#define ITEM_X_DEFEND_3
#define ITEM_X_SPECIAL_3
#define ITEM_X_SP_DEF_3
#define ITEM_X_SPEED_3
#define ITEM_DIRE_HIT_4
#define ITEM_X_ACCURACY_4
#define ITEM_X_ATTACK_4
#define ITEM_X_DEFEND_4
#define ITEM_X_SPECIAL_4
#define ITEM_X_SP_DEF_4
#define ITEM_X_SPEED_4
#define ITEM_DIRE_HIT_5
#define ITEM_X_ACCURACY_5
#define ITEM_X_ATTACK_5
#define ITEM_X_DEFEND_5
#define ITEM_X_SPECIAL_5
#define ITEM_X_SP_DEF_5
#define ITEM_X_SPEED_5
#define ITEM_DIRE_HIT_6
#define ITEM_X_ACCURACY_6
#define ITEM_X_ATTACK_6
#define ITEM_X_DEFEND_6
#define ITEM_X_SPECIAL_6
#define ITEM_X_SP_DEF_6
#define ITEM_X_SPEED_6
#define ITEM_ABILITY_URGE
#define ITEM_ITEM_DROP
#define ITEM_ITEM_URGE
#define ITEM_RESET_URGE
#define ITEM_WEAKNESS_POLICY
#define ITEM_ASSAULT_VEST
#define ITEM_WHIPPED_DREAM
#define ITEM_SACHET
#define ITEM_LUMINOUS_MOSS
#define ITEM_SNOWBALL
#define ITEM_SAFETY_GOGGLES
#define ITEM_GENGARITE
#define ITEM_GARDEVOIRITE
#define ITEM_AMPHAROSITE
#define ITEM_VENUSAURITE
#define ITEM_CHARIZARDITE_X
#define ITEM_CHARIZARDITE_Y
#define ITEM_BLASTOISINITE
#define ITEM_MEWTWONITE_X
#define ITEM_MEWTWONITE_Y
#define ITEM_BLAZIKENITE
#define ITEM_MEDICHAMITE
#define ITEM_HOUNDOOMITE
#define ITEM_AGGRONITE
#define ITEM_BANETTITE
#define ITEM_TYRANITARITE
#define ITEM_SCIZORITE
#define ITEM_PINSIRITE
#define ITEM_AERODACTYLITE
#define ITEM_LUCARIONITE
#define ITEM_ABOMASITE
#define ITEM_KANGASKHANITE
#define ITEM_GYARADOSITE
#define ITEM_ABSOLITE
#define ITEM_ALAKAZITE
#define ITEM_HERACRONITE
#define ITEM_MAWILITE
#define ITEM_MANECTITE
#define ITEM_GARCHOMPITE
#define ITEM_LATIASITE
#define ITEM_LATIOSITE
#define ITEM_SWAMPERTITE
#define ITEM_SCEPTILITE
#define ITEM_SABLENITE
#define ITEM_ALTARIANITE
#define ITEM_GALLADITE
#define ITEM_AUDINITE
#define ITEM_METAGROSSITE
#define ITEM_SHARPEDONITE
#define ITEM_SLOWBRONITE
#define ITEM_STEELIXITE
#define ITEM_PIDGEOTITE
#define ITEM_GLALITITE
#define ITEM_DIANCITE
#define ITEM_CAMERUPTITE
#define ITEM_LOPUNNITE
#define ITEM_SALAMENCITE
#define ITEM_BEEDRILLITE
#define ITEM_DISCOUNT_COUPON
#define ITEM_STRANGE_SOUVENIR
#define ITEM_TERRAIN_EXTENDER
#define ITEM_PROTECTIVE_PADS
#define ITEM_ELECTRIC_SEED
#define ITEM_PSYCHIC_SEED
#define ITEM_MISTY_SEED
#define ITEM_GRASSY_SEED
#define ITEM_FIGHTING_MEMORY
#define ITEM_FLYING_MEMORY
#define ITEM_POISON_MEMORY
#define ITEM_GROUND_MEMORY
#define ITEM_ROCK_MEMORY
#define ITEM_BUG_MEMORY
#define ITEM_GHOST_MEMORY
#define ITEM_STEEL_MEMORY
#define ITEM_FIRE_MEMORY
#define ITEM_WATER_MEMORY
#define ITEM_GRASS_MEMORY
#define ITEM_ELECTRIC_MEMORY
#define ITEM_PSYCHIC_MEMORY
#define ITEM_ICE_MEMORY
#define ITEM_DRAGON_MEMORY
#define ITEM_DARK_MEMORY
#define ITEM_FAIRY_MEMORY


// TMs/HMs
#define ITEM_TM01_FOCUS_PUNCH 289
#define ITEM_TM02_DRAGON_CLAW 290
#define ITEM_TM03_WATER_PULSE 291
#define ITEM_TM04_CALM_MIND 292
#define ITEM_TM05_ROAR 293
#define ITEM_TM06_TOXIC 294
#define ITEM_TM07_HAIL 295
#define ITEM_TM08_BULK_UP 296
#define ITEM_TM09_BULLET_SEED 297
#define ITEM_TM10_HIDDEN_POWER 298
#define ITEM_TM11_SUNNY_DAY 299
#define ITEM_TM12_TAUNT 300
#define ITEM_TM13_ICE_BEAM 301
#define ITEM_TM14_BLIZZARD 302
#define ITEM_TM15_HYPER_BEAM 303
#define ITEM_TM16_LIGHT_SCREEN 304
#define ITEM_TM17_PROTECT 305
#define ITEM_TM18_RAIN_DANCE 306
#define ITEM_TM19_GIGA_DRAIN 307
#define ITEM_TM20_SAFEGUARD 308
#define ITEM_TM21_FRUSTRATION 309
#define ITEM_TM22_SOLARBEAM 310
#define ITEM_TM23_IRON_TAIL 311
#define ITEM_TM24_THUNDERBOLT 312
#define ITEM_TM25_THUNDER 313
#define ITEM_TM26_EARTHQUAKE 314
#define ITEM_TM27_RETURN 315
#define ITEM_TM28_DIG 316
#define ITEM_TM29_PSYCHIC 317
#define ITEM_TM30_SHADOW_BALL 318
#define ITEM_TM31_BRICK_BREAK 319
#define ITEM_TM32_DOUBLE_TEAM 320
#define ITEM_TM33_REFLECT 321
#define ITEM_TM34_SHOCK_WAVE 322
#define ITEM_TM35_FLAMETHROWER 323
#define ITEM_TM36_SLUDGE_BOMB 324
#define ITEM_TM37_SANDSTORM 325
#define ITEM_TM38_FIRE_BLAST 326
#define ITEM_TM39_ROCK_TOMB 327
#define ITEM_TM40_AERIAL_ACE 328
#define ITEM_TM41_TORMENT 329
#define ITEM_TM42_FACADE 330
#define ITEM_TM43_SECRET_POWER 331
#define ITEM_TM44_REST 332
#define ITEM_TM45_ATTRACT 333
#define ITEM_TM46_THIEF 334
#define ITEM_TM47_STEEL_WING 335
#define ITEM_TM48_SKILL_SWAP 336
#define ITEM_TM49_SNATCH 337
#define ITEM_TM50_OVERHEAT 338
#define ITEM_TM51
#define ITEM_TM52
#define ITEM_TM53
#define ITEM_TM54
#define ITEM_TM55
#define ITEM_TM56
#define ITEM_TM57
#define ITEM_TM58
#define ITEM_TM59
#define ITEM_TM60
#define ITEM_TM61
#define ITEM_TM62
#define ITEM_TM63
#define ITEM_TM64
#define ITEM_TM65
#define ITEM_TM66
#define ITEM_TM67
#define ITEM_TM68
#define ITEM_TM69
#define ITEM_TM70
#define ITEM_TM71
#define ITEM_TM72
#define ITEM_TM73
#define ITEM_TM74
#define ITEM_TM75
#define ITEM_TM76
#define ITEM_TM77
#define ITEM_TM78
#define ITEM_TM79
#define ITEM_TM80
#define ITEM_TM81
#define ITEM_TM82
#define ITEM_TM83
#define ITEM_TM84
#define ITEM_TM85
#define ITEM_TM86
#define ITEM_TM87
#define ITEM_TM88
#define ITEM_TM89
#define ITEM_TM90
#define ITEM_TM91
#define ITEM_TM92
#define ITEM_TM93
#define ITEM_TM94
#define ITEM_TM95
#define ITEM_TM96
#define ITEM_TM97
#define ITEM_TM98
#define ITEM_TM99
#define ITEM_TM100
#define ITEM_HM01_CUT 339
#define ITEM_HM02_FLY 340
#define ITEM_HM03_SURF 341
#define ITEM_HM04_STRENGTH 342
#define ITEM_HM05_FLASH 343
#define ITEM_HM06_ROCK_SMASH 344
#define ITEM_HM07_WATERFALL 345
#define ITEM_HM08_DIVE 346

// Key Items
#define ITEM_EXPLORER_KIT
#define ITEM_LOOT_SACK
#define ITEM_RULE_BOOK
#define ITEM_POKE_RADAR
#define ITEM_POINT_CARD
#define ITEM_JOURNAL
#define ITEM_SEAL_CASE
#define ITEM_FASHION_CASE
#define ITEM_SEAL_BAG
#define ITEM_PAL_PAD
#define ITEM_WORKS_KEY
#define ITEM_OLD_CHARM
#define ITEM_GALACTIC_KEY
#define ITEM_RED_CHAIN
#define ITEM_TOWN_MAP
#define ITEM_VS_SEEKER
#define ITEM_COIN_CASE 260
#define ITEM_OLD_ROD 262
#define ITEM_GOOD_ROD 263
#define ITEM_SUPER_ROD 264
#define ITEM_WAILMER_PAIL 268
#define ITEM_POFFIN_CASE
#define ITEM_BIKE
#define ITEM_MACH_BIKE 259
#define ITEM_ACRO_BIKE 272
#define ITEM_SUITE_KEY
#define ITEM_OAKS_LETTER
#define ITEM_LUNAR_WING
#define ITEM_MEMBER_CARD
#define ITEM_AZURE_FLUTE
#define ITEM_SS_TICKET 265
#define ITEM_CONTEST_PASS 266
#define ITEM_MAGMA_STONE
#define ITEM_DEVON_GOODS 269
#define ITEM_COUPON_1
#define ITEM_COUPON_2
#define ITEM_COUPON_3
#define ITEM_STORAGE_KEY 285
#define ITEM_SECRET_POTION
#define ITEM_VS_RECORDER
#define ITEM_GRACIDEA
#define ITEM_SECRET_KEY
#define ITEM_APRICORN_BOX
#define ITEM_UNOWN_REPORT
#define ITEM_BERRY_POTS
#define ITEM_ITEMFINDER 261
#define ITEM_BLUE_CARD
#define ITEM_SLOWPOKE_TAIL
#define ITEM_CLEAR_BELL
#define ITEM_CARD_KEY
#define ITEM_BASEMENT_KEY 271
#define ITEM_SQUIRT_BOTTLE
#define ITEM_RED_SCALE
#define ITEM_LOST_ITEM
#define ITEM_PASS
#define ITEM_MACHINE_PART
#define ITEM_SILVER_WING
#define ITEM_RAINBOW_WING
#define ITEM_MYSTERY_EGG
#define ITEM_PHOTO_ALBUM
#define ITEM_GB_SOUNDS
#define ITEM_TIDAL_BELL
#define ITEM_RAGE_CANDY_BAR
#define ITEM_JADE_ORB
#define ITEM_LOCK_CAPSULE
#define ITEM_RED_ORB 276
#define ITEM_BLUE_ORB 277
#define ITEM_ENIGMA_STONE
#define ITEM_LIBERTY_PASS
#define ITEM_PROP_CASE
#define ITEM_DRAGON_SKULL
#define ITEM_LIGHT_STONE
#define ITEM_DARK_STONE
#define ITEM_XTRANSCEIVER
#define ITEM_MEDAL_BOX
#define ITEM_DNA_SPLICERS_B // for black kyurem
#define ITEM_DNA_SPLICERS_W // for white kyurem
#define ITEM_PERMIT
#define ITEM_OVAL_CHARM
#define ITEM_SHINY_CHARM
#define ITEM_PLASMA_CARD
#define ITEM_GRUBBY_HANKEY
#define ITEM_COLRESS_MACHINE
#define ITEM_REVEAL_GLASS
#define ITEM_POWER_PLANT_PASS
#define ITEM_MEGA_RING
#define ITEM_MEGA_CHARM
#define ITEM_MEGA_GLOVE
#define ITEM_MEGA_BRACELET
#define ITEM_MEGA_PENDANT
#define ITEM_MEGA_GLASSES
#define ITEM_MEGA_ANCHOR
#define ITEM_MEGA_STICKPIN
#define ITEM_MEGA_TIARA
#define ITEM_MEGA_ANKLET
#define ITEM_MEGA_CUFF
#define ITEM_INTRIGUING_STONE
#define ITEM_COMMON_STONE
#define ITEM_ELEVATOR_KEY
#define ITEM_TMV_PASS
#define ITEM_HONOR_OF_KALOS
#define ITEM_ADVENTURE_RULES
#define ITEM_LENS_CASE
#define ITEM_MAKEUP_BAG
#define ITEM_TRAVEL_TRUNK
#define ITEM_LOOKER_TICKET
#define ITEM_HOLO_CASTER
#define ITEM_SOOT_SACK 270
#define ITEM_POKEBLOCK_CASE 273
#define ITEM_LETTER 274
#define ITEM_EON_TICKET 275
#define ITEM_SCANNER 278
#define ITEM_GO_GOGGLES 279
#define ITEM_METEORITE 280
#define ITEM_ROOM_1_KEY 281
#define ITEM_ROOM_2_KEY 282
#define ITEM_ROOM_4_KEY 283
#define ITEM_ROOM_6_KEY 284
#define ITEM_DEVON_SCOPE 288
#define ITEM_DEVON_SCUBA_GEAR
#define ITEM_CONTEST_COSTUME_M
#define ITEM_CONTEST_COSTUME_F
#define ITEM_MAGMA_SUIT
#define ITEM_AQUA_SUIT
#define ITEM_PAIR_OF_TICKETS
#define ITEM_PRISON_BOTTLE
#define ITEM_KEY_STONE
#define ITEM_METEORITE_SHARD
#define ITEM_EON_FLUTE
#define ITEM_Z_RING
#define ITEM_FORAGE_BAG
#define ITEM_PROFESSORS_MASK
#define ITEM_FESTIVAL_TICKET
#define ITEM_SPARKLING_STONE
#define ITEM_ZYGARDE_CUBE
#define ITEM_RIDE_PAGER
#define ITEM_SUN_FLUTE
#define ITEM_MOON_FLUTE
#define ITEM_ENIGMATIC_CARD
#define ITEM_Z_POWER_RING
#define ITEM_PINK_PETAL
#define ITEM_ORANGE_PETAL
#define ITEM_BLUE_PETAL
#define ITEM_RED_PETAL
#define ITEM_GREEN_PETAL
#define ITEM_YELLOW_PETAL
#define ITEM_PURPLE_PETAL
#define ITEM_RAINBOW_FLOWER
#define ITEM_SURGE_BADGE
#define ITEM_N_SOLARIZER
#define ITEM_N_LUNARIZER
#define ITEM_LEFT_POKE_BALL

// z crystals
#define ITEM_NORMALIUM_Z
#define ITEM_FIRIUM_Z
#define ITEM_WATERIUM_Z
#define ITEM_ELECTRIUM_Z
#define ITEM_GRASSIUM_Z
#define ITEM_ICIUM_Z
#define ITEM_FIGHTNIUM_Z
#define ITEM_POISONIUM_Z
#define ITEM_GROUNDIUM_Z
#define ITEM_FLYINIUM_Z
#define ITEM_PSYCHIUM_Z
#define ITEM_BUGINIUM_Z
#define ITEM_ROCKIUM_Z
#define ITEM_GHOSTIUM_Z
#define ITEM_DRAGONIUM_Z
#define ITEM_DARKINIUM_Z
#define ITEM_STEELIUM_Z
#define ITEM_FAIRIUM_Z
#define ITEM_PIKANIUM_Z
#define ITEM_DECIDIUM_Z
#define ITEM_INCINIUM_Z
#define ITEM_PRIMARIUM_Z
#define ITEM_TAPUNIUM_Z
#define ITEM_MARSHADIUM_Z
#define ITEM_ALORAICHIUM_Z
#define ITEM_SNORLIUM_Z
#define ITEM_EEVIUM_Z
#define ITEM_MEWNIUM_Z
#define ITEM_PIKASHUNIUM_Z
#define ITEM_SOLGANIUM_Z
#define ITEM_LUNALIUM_Z
#define ITEM_UTRANECRONIUM_Z
#define ITEM_MIMIKIUM_Z
#define ITEM_LYCANIUM_Z
#define ITEM_KOMMONIUM_Z
#define ITEM_NORMALIUM_Z_2
#define ITEM_FIRIUM_Z_2
#define ITEM_WATERIUM_Z_2
#define ITEM_ELECTRIUM_Z_2
#define ITEM_GRASSIUM_Z_2
#define ITEM_ICIUM_Z_2
#define ITEM_FIGHTNIUM_Z_2
#define ITEM_POISONIUM_Z_2
#define ITEM_GROUNDIUM_Z_2
#define ITEM_FLYINIUM_Z_2
#define ITEM_PSYCHIUM_Z_2
#define ITEM_BUGINIUM_Z_2
#define ITEM_ROCKIUM_Z_2
#define ITEM_GHOSTIUM_Z_2
#define ITEM_DRAGONIUM_Z_2
#define ITEM_DARKINIUM_Z_2
#define ITEM_STEELIUM_Z_2
#define ITEM_FAIRIUM_Z_2
#define ITEM_PIKANIUM_Z_2
#define ITEM_DECIDIUM_Z_2
#define ITEM_INCINIUM_Z_2
#define ITEM_PRIMARIUM_Z_2
#define ITEM_TAPUNIUM_Z_2
#define ITEM_MARSHADIUM_Z_2
#define ITEM_ALORAICHIUM_Z_2
#define ITEM_SNORLIUM_Z_2
#define ITEM_EEVIUM_Z_2
#define ITEM_MEWNIUM_Z_2
#define ITEM_PIKASHUNIUM_Z_2
#define ITEM_SOLGANIUM_Z_2
#define ITEM_LUNALIUM_Z_2
#define ITEM_UTRANECRONIUM_Z_2
#define ITEM_MIMIKIUM_Z_2
#define ITEM_LYCANIUM_Z_2
#define ITEM_KOMMONIUM_Z_2


// Ball IDs (lookup table)
#define BALLID_MASTER_BALL 4
#define BALLID_ULTRA_BALL 3
#define BALLID_GREAT_BALL 1
#define BALLID_POKE_BALL 0
#define BALLID_SAFARI_BALL 2
#define BALLID_NET_BALL 5
#define BALLID_DIVE_BALL 6
#define BALLID_NEST_BALL 7
#define BALLID_REPEAT_BALL 8
#define BALLID_TIMER_BALL 9
#define BALLID_LUXURY_BALL 10
#define BALLID_PREMIER_BALL 11
#define BALLID_LEVEL_BALL 12
#define BALLID_LURE_BALL 13
#define BALLID_MOON_BALL 14
#define BALLID_FRIEND_BALL 15
#define BALLID_LOVE_BALL 16
#define BALLID_HEAVY_BALL 17
#define BALLID_FAST_BALL 18
#define BALLID_SPORT_BALL 19
#define BALLID_HEAL_BALL 20
#define BALLID_QUICK_BALL 21
#define BALLID_DUSK_BALL 22
#define BALLID_CHERISH_BALL 23
#define BALLID_PARK_BALL 24
#define BALLID_DREAM_BALL 25
#define BALLID_BEAST_BALL 26

#define NUM_TECHNICAL_MACHINES 50
#define NUM_HIDDEN_MACHINES     8

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_MARANGA_BERRY)

#define IS_ITEM_MAIL(item) ((item) >= ITEM_ORANGE_MAIL && (item) <= ITEM_RETRO_MAIL)

#endif  // GUARD_CONSTANTS_ITEMS_H
