gAbilityNames:: @ 81FA248

@@@@@@@@@@@
@ GEN III @
@@@@@@@@@@@

	.string "-------$", 13
	.string "Stench$", 13
	.string "Drizzle$", 13
	.string "Speed Boost$", 13
	.string "Battle Armor$", 13
	.string "Sturdy$", 13
	.string "Damp$", 13
	.string "Limber$", 13
	.string "Sand Veil$", 13
	.string "Static$", 13
	.string "Volt Absorb$", 13
	.string "Water Absorb$", 13
	.string "Oblivious$", 13
	.string "Cloud Nine$", 13
	.string "Compund Eyes$", 13
	.string "Insomnia$", 13
	.string "Color Change$", 13
	.string "Immunity$", 13
	.string "Flash Fire$", 13
	.string "Shield Dust$", 13
	.string "Own Tempo$", 13
	.string "Suction Cups$", 13
	.string "Intimidate$", 13
	.string "Shadow Tag$", 13
	.string "Rough Skin$", 13
	.string "Wonder Guard$", 13
	.string "Levitate$", 13
	.string "Effect Spore$", 13
	.string "Synchronize$", 13
	.string "Clear Boy$", 13
	.string "Natural Cure$", 13
	.string "LightningRod$", 13
	.string "Serene Grace$", 13
	.string "Swift Swim$", 13
	.string "Chlorophyll$", 13
	.string "Illuminate$", 13
	.string "Trace$", 13
	.string "Huge Power$", 13
	.string "Poison Point$", 13
	.string "Inner Focus$", 13
	.string "Magma Armor$", 13
	.string "Water Veil$", 13
	.string "Magnet Pull$", 13
	.string "Soundproof$", 13
	.string "Rain Dish$", 13
	.string "Sand Stream$", 13
	.string "Pressure$", 13
	.string "Thick Fat$", 13
	.string "Early Bird$", 13
	.string "Flame Body$", 13
	.string "Run Away$", 13
	.string "Keen Eye$", 13
	.string "Hyper Cutter$", 13
	.string "Pickup$", 13
	.string "Truant$", 13
	.string "Hustle$", 13
	.string "Cute Charm$", 13
	.string "Plus$", 13
	.string "Minus$", 13
	.string "Forecast$", 13
	.string "Sticky Hold$", 13
	.string "Shed Skin$", 13
	.string "Guts$", 13
	.string "Marvel Scale$", 13
	.string "Liquid Ooze$", 13
	.string "Overgrow$", 13
	.string "Blaze$", 13
	.string "Torrent$", 13
	.string "Swarm$", 13
	.string "Rock Head$", 13
	.string "Drought$", 13
	.string "Arena Trap$", 13
	.string "Vital Spirit$", 13
	.string "White Smoke$", 13
	.string "Pure Power$", 13
	.string "Shell Armor$", 13
	.string "Cacophony$", 13
	.string "Air Lock$", 13

@@@@@@@@@@
@ GEN IV @
@@@@@@@@@@	

	.string "Tangled Feet$", 13
	.string "Motor Drive$", 13
	.string "Rivalry$", 13
	.string "Steadfast$", 13
	.string "Snow Cloak$", 13
	.string "Gluttony$", 13
	.string "Anger Point$", 13
	.string "Unburden$", 13
	.string "Heatproof$", 13
	.string "Simple$", 13
	.string "Dry Skin$", 13
	.string "Download$", 13
	.string "Iron Fist$", 13
	.string "Poison Heal$", 13
	.string "Adaptability$", 13
	.string "Skill Link$", 13
	.string "Hydration$", 13
	.string "Solar Power$", 13
	.string "Quick Feet$", 13
	.string "Normalize$", 13
	.string "Sniper$", 13
	.string "Magic Guard$", 13
	.string "No Guard$", 13
	.string "Stall$", 13
	.string "Technician$", 13
	.string "Leaf Guard$", 13
	.string "Klutz$", 13
	.string "Mold Breaker$", 13
	.string "Super Luck$", 13
	.string "Aftermath$", 13
	.string "Anticipation$", 13
	.string "Forewarn$", 13
	.string "Unaware$", 13
	.string "Tinted Lens$", 13
	.string "Filter$", 13
	.string "Slow Start$", 13
	.string "Scrappy$", 13
	.string "Storm Drain$", 13
	.string "Ice Body$", 13
	.string "Solid Rock$", 13
	.string "Snow Warning$", 13
	.string "Honey Gather$", 13
	.string "Frisk$", 13
	.string "Reckless$", 13
	.string "Multitype$", 13
	.string "Flower Gift$", 13
	.string "Bad Dreams$", 13

@@@@@@@@@
@ GEN V @
@@@@@@@@@

	.string "Pickpocket$", 13
	.string "Sheer Force$", 13
	.string "Contrary$", 13
	.string "Unnerve$", 13
	.string "Defiant$", 13
	.string "Defeatist$", 13
	.string "Cursed Body$", 13
	.string "Healer$", 13
	.string "Friend Guard$", 13
	.string "Weak Armor$", 13
	.string "Heavy Metal$", 13
	.string "Light Metal$", 13
	.string "Multiscale$", 13
	.string "Toxic Boost$", 13
	.string "Flare Boost$", 13
	.string "Harvest$", 13
	.string "Telepathy$", 13
	.string "Moody$", 13
	.string "Overcoat$", 13
	.string "Poison Touch$", 13
	.string "Regenerator$", 13
	.string "Big Pecks$", 13
	.string "Sand Rush$", 13
	.string "Wonder Skin$", 13
	.string "Analytic$", 13
	.string "Illusion$", 13
	.string "Imposter$", 13
	.string "Infiltrator$", 13
	.string "Mummy$", 13
	.string "Moxie$", 13
	.string "Justified$", 13
	.string "Rattled$", 13
	.string "Magic Bounce$", 13
	.string "Sap Sipper$", 13
	.string "Prankster$", 13
	.string "Sand Force$", 13
	.string "Iron Barbs$", 13
	.string "Zen Mode$", 13
	.string "Victory Star$", 13
	.string "Turboblaze$", 13
	.string "Teravolt$", 13

@@@@@@@@@@
@ GEN VI @
@@@@@@@@@@

	.string "Aroma Veil$", 13
	.string "Flower Veil$", 13
	.string "Cheek Pouch$", 13
	.string "Protean$", 13
	.string "Fur Coat$", 13
	.string "Magician$", 13
	.string "Bulletproof$", 13
	.string "Competitive$", 13
	.string "Strong Jaw$", 13
	.string "Refrigerate$", 13
	.string "Sweet Veil$", 13
	.string "StanceChange$", 13
	.string "Gale Wings$", 13
	.string "MegaLauncher$", 13
	.string "Grass Pelt$", 13
	.string "Symbiosis$", 13
	.string "Tough Claws$", 13
	.string "Pixilate$", 13
	.string "Gooey$", 13
	.string "Aerilate$", 13
	.string "ParentalBond$", 13
	.string "Dark Aura$", 13
	.string "Fairy Aura$", 13
	.string "Aura Break$", 13
	.string "Primal Sea$", 13   @Primordial Sea
	.string "DesolateLand$", 13
	.string "Delta Stream$", 13

@@@@@@@@@@@
@ GEN VII @
@@@@@@@@@@@

	.string "Stamina$", 13
	.string "Wimp Out$", 13
	.string "Crisis Exit$", 13  @Emergency Exit
	.string "WaterDefense$", 13 @Water Compaction
	.string "Merciless$", 13
	.string "Shields Down$", 13
	.string "Stakeout$", 13
	.string "Water Bubble$", 13
	.string "Steelworker$", 13
	.string "Berserk$", 13
	.string "Slush Rush$", 13
	.string "Long Reach$", 13
	.string "Liquid Voice$", 13
	.string "Triage$", 13
	.string "Galvanize$", 13
	.string "Surge Surfer$", 13
	.string "Schooling$", 13
	.string "Disguise$", 13
	.string "Battle Bond$", 13
	.string "Power Change$", 13 @Power Construct
	.string "Corrosion$", 13
	.string "Comatose$", 13
	.string "Queenly Aura$", 13 @Queenly Majesty
	.string "Innards Out$", 13
	.string "Dancer$", 13
	.string "Battery$", 13
	.string "Fluffy$", 13
	.string "Dazzling$", 13
	.string "Soul Heart$", 13
	.string "Tangled Hair$", 13 @Tangling Hair
	.string "Receiver$", 13
	.string "AlchemyPower$", 13 @Power of Alchemy
	.string "Beast Boost$", 13
	.string "RKS System$", 13
	.string "ElectrcSurge$", 13 @Electric Surge
	.string "PsychicSurge$", 13 @Psychic Surge
	.string "Misty Surge$", 13
	.string "Grassy Surge$", 13
	.string "Metal Body$", 13   @Full Metal Body
	.string "ShadowShield$", 13
	.string "Prism Armor$", 13
