@@@@@@@@@@@
@ GEN III @
@@@@@@@@@@@

gAbilityDescription_None: @ 81F99CC
	.string "No special ability.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Helps repel wild Pokémon.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Summons rain in battle.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Gradually boosts Speed.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "Blocks critical hits.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Negates 1-hit KO attacks.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Prevents self-destruction.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Prevents paralysis.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "Ups evasion in a sandstorm.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "Paralyzes on contact.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Turns electricity into HP.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Changes water into HP.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Prevents attraction.$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "Negates weather effects.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Raises accuracy.$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "Prevents sleep.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Changes type to foe’s move.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Prevents poisoning.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Powers up if hit by fire.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Prevents added effects.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Prevents confusion.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Firmly anchors the body.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Lowers the foe’s Attack.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Prevents the foe’s escape.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Hurts to touch.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "“Super effective” hits.$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "Not hit by Ground attacks.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "Leaves spores on contact.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Passes on status problems.$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "Prevents ability reduction.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Heals upon switching out.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Draws electrical moves.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Promotes added effects.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Raises Speed in rain.$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "Raises Speed in sunshine.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Encounter rate increases.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Copies special ability.$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "Raises Attack.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "Poisons foe on contact.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Prevents flinching.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Prevents freezing.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Prevents burns.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Traps STEEL-type Pokémon.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Avoids sound-based moves.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "Slight HP recovery in rain.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Summons a sandstorm.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Raises foe’s PP usage.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Heat-and-cold protection.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Awakens quickly from sleep.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "Burns the foe on contact.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Makes escaping easier.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Prevents loss of accuracy.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Prevents Attack reduction.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "May pick up items.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Moves only every two turns.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Trades accuracy for power.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "Infatuates on contact.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Powers up with Minus.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Powers up with Plus.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Changes with the weather.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Prevents item theft.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "Heals the body by shedding.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "Ups Attack if suffering.$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "Ups Defense if suffering.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Draining causes injury.$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "Ups Grass moves in a pinch.$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "Ups Fire moves in a pinch.$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "Ups Water moves in a pinch.$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "Ups Bug moves in a pinch.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Prevents recoil damage.$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Summons sunlight in battle.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Prevents fleeing.$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Prevents sleep.$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Prevents ability reduction.$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "Raises Attack.$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Blocks critical hits.$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "Avoids sound-based moves.$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "Negates weather effects.$"

@@@@@@@@@@
@ GEN IV @
@@@@@@@@@@

gAbilityDescription_TangledFeet:
	.string ".$"

gAbilityDescription_MotorDrive:
	.string ".$"

gAbilityDescription_Rivalry:
	.string ".$"

gAbilityDescription_Steadfast:
	.string ".$"

gAbilityDescription_SnowCloak:
	.string ".$"

gAbilityDescription_Gluttony:
	.string ".$"

gAbilityDescription_AngerPoint:
	.string ".$"

gAbilityDescription_Unburden:
	.string ".$"

gAbilityDescription_Heatproof:
	.string ".$"

gAbilityDescription_Simple:
	.string ".$"

gAbilityDescription_DrySkin:
	.string ".$"

gAbilityDescription_Download:
	.string ".$"

gAbilityDescription_IronFist:
	.string ".$"

gAbilityDescription_PoisonHeal:
	.string ".$"

gAbilityDescription_Adaptability:
	.string ".$"

gAbilityDescription_SkillLink:
	.string ".$"

gAbilityDescription_Hydration:
	.string ".$"

gAbilityDescription_SolarPower:
	.string ".$"

gAbilityDescription_QuickFeet:
	.string ".$"

gAbilityDescription_Normalize:
	.string ".$"

gAbilityDescription_Sniper:
	.string ".$"

gAbilityDescription_MagicGuard:
	.string ".$"

gAbilityDescription_NoGuard:
	.string ".$"

gAbilityDescription_Stall:
	.string ".$"

gAbilityDescription_Technician:
	.string ".$"

gAbilityDescription_LeafGuard:
	.string ".$"

gAbilityDescription_Klutz:
	.string ".$"

gAbilityDescription_MoldBreaker:
	.string ".$"

gAbilityDescription_SuperLuck:
	.string ".$"

gAbilityDescription_Aftermath:
	.string ".$"

gAbilityDescription_Anticipation:
	.string ".$"

gAbilityDescription_Forewarn:
	.string ".$"

gAbilityDescription_Unaware:
	.string ".$"

gAbilityDescription_TintedLens:
	.string ".$"

gAbilityDescription_Filter:
	.string ".$"

gAbilityDescription_SlowStart:
	.string ".$"

gAbilityDescription_Scrappy:
	.string ".$"

gAbilityDescription_StormDrain:
	.string ".$"

gAbilityDescription_IceBody:
	.string ".$"

gAbilityDescription_SolidRock:
	.string ".$"

gAbilityDescription_SnowWarning:
	.string ".$"

gAbilityDescription_HoneyGather:
	.string ".$"

gAbilityDescription_Frisk:
	.string ".$"

gAbilityDescription_Reckless:
	.string ".$"

gAbilityDescription_Multitype:
	.string ".$"

gAbilityDescription_FlowerGift:
	.string ".$"

gAbilityDescription_BadDreams:
	.string ".$"

@@@@@@@@@
@ GEN V @
@@@@@@@@@

gAbilityDescription_Pickpocket:
	.string ".$"

gAbilityDescription_SheerForce:
	.string ".$"

gAbilityDescription_Contrary:
	.string ".$"

gAbilityDescription_Unnerve:
	.string ".$"

gAbilityDescription_Defiant:
	.string ".$"

gAbilityDescription_Defeatist:
	.string ".$"

gAbilityDescription_CursedBody:
	.string ".$"

gAbilityDescription_Healer:
	.string ".$"

gAbilityDescription_FriendGuard:
	.string ".$"

gAbilityDescription_WeakArmor:
	.string ".$"

gAbilityDescription_HeavyMetal:
	.string ".$"

gAbilityDescription_LightMetal:
	.string ".$"

gAbilityDescription_Multiscale:
	.string ".$"

gAbilityDescription_ToxicBoost:
	.string ".$"

gAbilityDescription_FlareBoost:
	.string ".$"

gAbilityDescription_Harvest:
	.string ".$"

gAbilityDescription_Telepathy:
	.string ".$"

gAbilityDescription_Moody:
	.string ".$"

gAbilityDescription_Overcoat:
	.string ".$"

gAbilityDescription_PoisonTouch:
	.string ".$"

gAbilityDescription_Regenerator:
	.string ".$"

gAbilityDescription_BigPecks:
	.string ".$"

gAbilityDescription_SandRush:
	.string ".$"

gAbilityDescription_WonderSkin:
	.string ".$"

gAbilityDescription_Analytic:
	.string ".$"

gAbilityDescription_Illusion:
	.string ".$"

gAbilityDescription_Imposter:
	.string ".$"

gAbilityDescription_Infiltrator:
	.string ".$"

gAbilityDescription_Mummy:
	.string ".$"

gAbilityDescription_Moxie:
	.string ".$"

gAbilityDescription_Justified:
	.string ".$"

gAbilityDescription_Rattled:
	.string ".$"

gAbilityDescription_MagicBounce:
	.string ".$"

gAbilityDescription_SapSipper:
	.string ".$"

gAbilityDescription_Prankster:
	.string ".$"

gAbilityDescription_SandForce:
	.string ".$"

gAbilityDescription_IronBarbs:
	.string ".$"

gAbilityDescription_ZenMode:
	.string ".$"

gAbilityDescription_VictoryStar:
	.string ".$"

gAbilityDescription_Turboblaze:
	.string ".$"

gAbilityDescription_Teravolt:
	.string ".$"

@@@@@@@@@@
@ GEN VI @
@@@@@@@@@@

gAbilityDescription_AromaVeil:
	.string ".$"

gAbilityDescription_FlowerVeil:
	.string ".$"

gAbilityDescription_CheekPouch:
	.string ".$"

gAbilityDescription_Protean:
	.string ".$"

gAbilityDescription_FurCoat:
	.string ".$"

gAbilityDescription_Magician:
	.string ".$"

gAbilityDescription_Bulletproof:
	.string ".$"

gAbilityDescription_Competitive:
	.string ".$"

gAbilityDescription_StrongJaw:
	.string ".$"

gAbilityDescription_Refrigerate:
	.string ".$"

gAbilityDescription_SweetVeil:
	.string ".$"

gAbilityDescription_StanceChange:
	.string ".$"

gAbilityDescription_GaleWings:
	.string ".$"

gAbilityDescription_MegaLauncher:
	.string ".$"

gAbilityDescription_GrassPelt:
	.string ".$"

gAbilityDescription_Symbiosis:
	.string ".$"

gAbilityDescription_ToughClaws:
	.string ".$"

gAbilityDescription_Pixilate:
	.string ".$"

gAbilityDescription_Gooey:
	.string ".$"

gAbilityDescription_Aerilate:
	.string ".$"

gAbilityDescription_ParentalBond:
	.string ".$"

gAbilityDescription_DarkAura:
	.string ".$"

gAbilityDescription_FairyAura:
	.string ".$"

gAbilityDescription_AuraBreak:
	.string ".$"

gAbilityDescription_PrimordialSea:
	.string ".$"

gAbilityDescription_DesolateLand:
	.string ".$"

gAbilityDescription_DeltaStream:
	.string ".$"

@@@@@@@@@@@
@ GEN VII @
@@@@@@@@@@@

gAbilityDescription_Stamina:
	.string ".$"

gAbilityDescription_WimpOut:
	.string ".$"

gAbilityDescription_EmergencyExit:
	.string ".$"

gAbilityDescription_WaterCompaction:
	.string ".$"

gAbilityDescription_Merciless:
	.string ".$"

gAbilityDescription_ShieldsDown:
	.string ".$"

gAbilityDescription_Stakeout:
	.string ".$"

gAbilityDescription_WaterBubble:
	.string ".$"

gAbilityDescription_Steelworker:
	.string ".$"

gAbilityDescription_Berserk:
	.string ".$"

gAbilityDescription_SlushRush:
	.string ".$"

gAbilityDescription_LongReach:
	.string ".$"

gAbilityDescription_LiquidVoice:
	.string ".$"

gAbilityDescription_Triage:
	.string ".$"

gAbilityDescription_Galvanize:
	.string ".$"

gAbilityDescription_SurgeSurfer:
	.string ".$"

gAbilityDescription_Schooling:
	.string ".$"

gAbilityDescription_Disguise:
	.string ".$"

gAbilityDescription_BattleBond:
	.string ".$"

gAbilityDescription_PowerConstruct:
	.string ".$"

gAbilityDescription_Corrosion:
	.string ".$"

gAbilityDescription_Comatose:
	.string ".$"

gAbilityDescription_QueenlyMajesty:
	.string ".$"

gAbilityDescription_InnardsOut:
	.string ".$"

gAbilityDescription_Dancer:
	.string ".$"

gAbilityDescription_Battery:
	.string ".$"

gAbilityDescription_Fluffy:
	.string ".$"

gAbilityDescription_Dazzling:
	.string ".$"

gAbilityDescription_SoulHeart:
	.string ".$"

gAbilityDescription_TanglingHair:
	.string ".$"

gAbilityDescription_Receiver:
	.string ".$"

gAbilityDescription_PowerOfAlchemy:
	.string ".$"

gAbilityDescription_BeastBoost:
	.string ".$"

gAbilityDescription_RKSSystem:
	.string ".$"

gAbilityDescription_ElectricSurge:
	.string ".$"

gAbilityDescription_PsychicSurge:
	.string ".$"

gAbilityDescription_MistySurge:
	.string ".$"

gAbilityDescription_GrassySurge:
	.string ".$"

gAbilityDescription_FullMetalBody:
	.string ".$"

gAbilityDescription_ShadowShield:
	.string ".$"

gAbilityDescription_PrismArmor:
	.string ".$"

	.align 2
gAbilityDescriptions:: @ 81FA110

@@@@@@@@@@@
@ GEN III @
@@@@@@@@@@@

	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Cacophony
	.4byte gAbilityDescription_AirLock

@@@@@@@@@@
@ GEN IV @
@@@@@@@@@@

	.4byte gAbilityDescription_TangledFeet
	.4byte gAbilityDescription_MotorDrive
	.4byte gAbilityDescription_Rivalry
	.4byte gAbilityDescription_Steadfast
	.4byte gAbilityDescription_SnowCloak
	.4byte gAbilityDescription_Gluttony
	.4byte gAbilityDescription_AngerPoint
	.4byte gAbilityDescription_Unburden
	.4byte gAbilityDescription_Heatproof
	.4byte gAbilityDescription_Simple
	.4byte gAbilityDescription_DrySkin
	.4byte gAbilityDescription_Download
	.4byte gAbilityDescription_IronFist
	.4byte gAbilityDescription_PoisonHeal
	.4byte gAbilityDescription_Adaptability
	.4byte gAbilityDescription_SkillLink
	.4byte gAbilityDescription_Hydration
	.4byte gAbilityDescription_SolarPower
	.4byte gAbilityDescription_QuickFeet
	.4byte gAbilityDescription_Normalize
	.4byte gAbilityDescription_Sniper
	.4byte gAbilityDescription_MagicGuard
	.4byte gAbilityDescription_NoGuard
	.4byte gAbilityDescription_Stall
	.4byte gAbilityDescription_Technician
	.4byte gAbilityDescription_LeafGuard
	.4byte gAbilityDescription_Klutz
	.4byte gAbilityDescription_MoldBreaker
	.4byte gAbilityDescription_SuperLuck
	.4byte gAbilityDescription_Aftermath
	.4byte gAbilityDescription_Anticipation
	.4byte gAbilityDescription_Forewarn
	.4byte gAbilityDescription_Unaware
	.4byte gAbilityDescription_TintedLens
	.4byte gAbilityDescription_Filter
	.4byte gAbilityDescription_SlowStart
	.4byte gAbilityDescription_Scrappy
	.4byte gAbilityDescription_StormDrain
	.4byte gAbilityDescription_IceBody
	.4byte gAbilityDescription_SolidRock
	.4byte gAbilityDescription_SnowWarning
	.4byte gAbilityDescription_HoneyGather
	.4byte gAbilityDescription_Frisk
	.4byte gAbilityDescription_Reckless
	.4byte gAbilityDescription_Multitype
	.4byte gAbilityDescription_FlowerGift
	.4byte gAbilityDescription_BadDreams

@@@@@@@@@
@ GEN V @
@@@@@@@@@

	.4byte gAbilityDescription_Pickpocket
	.4byte gAbilityDescription_SheerForce
	.4byte gAbilityDescription_Contrary
	.4byte gAbilityDescription_Unnerve
	.4byte gAbilityDescription_Defiant
	.4byte gAbilityDescription_Defeatist
	.4byte gAbilityDescription_CursedBody
	.4byte gAbilityDescription_Healer
	.4byte gAbilityDescription_FriendGuard
	.4byte gAbilityDescription_WeakArmor
	.4byte gAbilityDescription_HeavyMetal
	.4byte gAbilityDescription_LightMetal
	.4byte gAbilityDescription_Multiscale
	.4byte gAbilityDescription_ToxicBoost
	.4byte gAbilityDescription_FlareBoost
	.4byte gAbilityDescription_Harvest
	.4byte gAbilityDescription_Telepathy
	.4byte gAbilityDescription_Moody
	.4byte gAbilityDescription_Overcoat
	.4byte gAbilityDescription_PoisonTouch
	.4byte gAbilityDescription_Regenerator
	.4byte gAbilityDescription_BigPecks
	.4byte gAbilityDescription_SandRush
	.4byte gAbilityDescription_WonderSkin
	.4byte gAbilityDescription_Analytic
	.4byte gAbilityDescription_Illusion
	.4byte gAbilityDescription_Imposter
	.4byte gAbilityDescription_Infiltrator
	.4byte gAbilityDescription_Mummy
	.4byte gAbilityDescription_Moxie
	.4byte gAbilityDescription_Justified
	.4byte gAbilityDescription_Rattled
	.4byte gAbilityDescription_MagicBounce
	.4byte gAbilityDescription_SapSipper
	.4byte gAbilityDescription_Prankster
	.4byte gAbilityDescription_SandForce
	.4byte gAbilityDescription_IronBarbs
	.4byte gAbilityDescription_ZenMode
	.4byte gAbilityDescription_VictoryStar
	.4byte gAbilityDescription_Turboblaze
	.4byte gAbilityDescription_Teravolt

@@@@@@@@@@
@ GEN VI @
@@@@@@@@@@

	.4byte gAbilityDescription_AromaVeil
	.4byte gAbilityDescription_FlowerVeil
	.4byte gAbilityDescription_CheekPouch
	.4byte gAbilityDescription_Protean
	.4byte gAbilityDescription_FurCoat
	.4byte gAbilityDescription_Magician
	.4byte gAbilityDescription_Bulletproof
	.4byte gAbilityDescription_Competitive
	.4byte gAbilityDescription_StrongJaw
	.4byte gAbilityDescription_Refrigerate
	.4byte gAbilityDescription_SweetVeil
	.4byte gAbilityDescription_StanceChange
	.4byte gAbilityDescription_GaleWings
	.4byte gAbilityDescription_MegaLauncher
	.4byte gAbilityDescription_GrassPelt
	.4byte gAbilityDescription_Symbiosis
	.4byte gAbilityDescription_ToughClaws
	.4byte gAbilityDescription_Pixilate
	.4byte gAbilityDescription_Gooey
	.4byte gAbilityDescription_Aerilate
	.4byte gAbilityDescription_ParentalBond
	.4byte gAbilityDescription_DarkAura
	.4byte gAbilityDescription_FairyAura
	.4byte gAbilityDescription_AuraBreak
	.4byte gAbilityDescription_PrimordialSea
	.4byte gAbilityDescription_DesolateLand
	.4byte gAbilityDescription_DeltaStream

@@@@@@@@@@@
@ GEN VII @
@@@@@@@@@@@

	.4byte gAbilityDescription_Stamina
	.4byte gAbilityDescription_WimpOut
	.4byte gAbilityDescription_EmergencyExit
	.4byte gAbilityDescription_WaterCompaction
	.4byte gAbilityDescription_Merciless
	.4byte gAbilityDescription_ShieldsDown
	.4byte gAbilityDescription_Stakeout
	.4byte gAbilityDescription_WaterBubble
	.4byte gAbilityDescription_Steelworker
	.4byte gAbilityDescription_Berserk
	.4byte gAbilityDescription_SlushRush
	.4byte gAbilityDescription_LongReach
	.4byte gAbilityDescription_LiquidVoice
	.4byte gAbilityDescription_Triage
	.4byte gAbilityDescription_Galvanize
	.4byte gAbilityDescription_SurgeSurfer
	.4byte gAbilityDescription_Schooling
	.4byte gAbilityDescription_Disguise
	.4byte gAbilityDescription_BattleBond
	.4byte gAbilityDescription_PowerConstruct
	.4byte gAbilityDescription_Corrosion
	.4byte gAbilityDescription_Comatose
	.4byte gAbilityDescription_QueenlyMajesty
	.4byte gAbilityDescription_InnardsOut
	.4byte gAbilityDescription_Dancer
	.4byte gAbilityDescription_Battery
	.4byte gAbilityDescription_Fluffy
	.4byte gAbilityDescription_Dazzling
	.4byte gAbilityDescription_SoulHeart
	.4byte gAbilityDescription_TanglingHair
	.4byte gAbilityDescription_Receiver
	.4byte gAbilityDescription_PowerOfAlchemy
	.4byte gAbilityDescription_BeastBoost
	.4byte gAbilityDescription_RKSSystem
	.4byte gAbilityDescription_ElectricSurge
	.4byte gAbilityDescription_PsychicSurge
	.4byte gAbilityDescription_MistySurge
	.4byte gAbilityDescription_GrassySurge
	.4byte gAbilityDescription_FullMetalBody
	.4byte gAbilityDescription_ShadowShield
	.4byte gAbilityDescription_PrismArmor
