#include "global.h"
#include "data2.h"
#include "constants/abilities.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/species.h"
#include "main.h"
#include "pokemon.h"
#include "pokemon_item_effect.h"
#include "random.h"
#include "overworld.h"
#include "sprite.h"
#include "string_util.h"
#include "trainer.h"
#include "text.h"
#include "ewram.h"
#include "util.h"

extern u16 gMoveToLearn;

static EWRAM_DATA u8 sLearningMoveTableID = 0;

u8 gPlayerPartyCount;
struct Pokemon gPlayerParty[6];
u8 gEnemyPartyCount;
struct Pokemon gEnemyParty[6];

#define SPECIES_TO_HOENN(name)      [SPECIES_##name - 1] = HOENN_DEX_##name
#define SPECIES_TO_NATIONAL(name)   [SPECIES_##name - 1] = NATIONAL_DEX_##name
#define HOENN_TO_NATIONAL(name)     [HOENN_DEX_##name - 1] = NATIONAL_DEX_##name

const u16 gSpeciesToHoennPokedexNum[NUM_SPECIES] = // Assigns all species to the Hoenn Dex Index (Summary No. for Hoenn Dex)
{
    SPECIES_TO_HOENN(TREECKO),
    SPECIES_TO_HOENN(GROVYLE),
    SPECIES_TO_HOENN(SCEPTILE),
    SPECIES_TO_HOENN(TORCHIC),
    SPECIES_TO_HOENN(COMBUSKEN),
    SPECIES_TO_HOENN(BLAZIKEN),
    SPECIES_TO_HOENN(MUDKIP),
    SPECIES_TO_HOENN(MARSHTOMP),
    SPECIES_TO_HOENN(SWAMPERT),
    SPECIES_TO_HOENN(POOCHYENA),
    SPECIES_TO_HOENN(MIGHTYENA),
    SPECIES_TO_HOENN(ZIGZAGOON),
    SPECIES_TO_HOENN(LINOONE),
    SPECIES_TO_HOENN(WURMPLE),
    SPECIES_TO_HOENN(SILCOON),
    SPECIES_TO_HOENN(BEAUTIFLY),
    SPECIES_TO_HOENN(CASCOON),
    SPECIES_TO_HOENN(DUSTOX),
    SPECIES_TO_HOENN(LOTAD),
    SPECIES_TO_HOENN(LOMBRE),
    SPECIES_TO_HOENN(LUDICOLO),
    SPECIES_TO_HOENN(SEEDOT),
    SPECIES_TO_HOENN(NUZLEAF),
    SPECIES_TO_HOENN(SHIFTRY),
    SPECIES_TO_HOENN(TAILLOW),
    SPECIES_TO_HOENN(SWELLOW),
    SPECIES_TO_HOENN(WINGULL),
    SPECIES_TO_HOENN(PELIPPER),
    SPECIES_TO_HOENN(RALTS),
    SPECIES_TO_HOENN(KIRLIA),
    SPECIES_TO_HOENN(GARDEVOIR),
    SPECIES_TO_HOENN(SURSKIT),
    SPECIES_TO_HOENN(MASQUERAIN),
    SPECIES_TO_HOENN(SHROOMISH),
    SPECIES_TO_HOENN(BRELOOM),
    SPECIES_TO_HOENN(SLAKOTH),
    SPECIES_TO_HOENN(VIGOROTH),
    SPECIES_TO_HOENN(SLAKING),
    SPECIES_TO_HOENN(ABRA),
    SPECIES_TO_HOENN(KADABRA),
    SPECIES_TO_HOENN(ALAKAZAM),
    SPECIES_TO_HOENN(NINCADA),
    SPECIES_TO_HOENN(NINJASK),
    SPECIES_TO_HOENN(SHEDINJA),
    SPECIES_TO_HOENN(WHISMUR),
    SPECIES_TO_HOENN(LOUDRED),
    SPECIES_TO_HOENN(EXPLOUD),
    SPECIES_TO_HOENN(MAKUHITA),
    SPECIES_TO_HOENN(HARIYAMA),
    SPECIES_TO_HOENN(GOLDEEN),
    SPECIES_TO_HOENN(SEAKING),
    SPECIES_TO_HOENN(MAGIKARP),
    SPECIES_TO_HOENN(GYARADOS),
    SPECIES_TO_HOENN(AZURILL),
    SPECIES_TO_HOENN(MARILL),
    SPECIES_TO_HOENN(AZUMARILL),
    SPECIES_TO_HOENN(GEODUDE),
    SPECIES_TO_HOENN(GRAVELER),
    SPECIES_TO_HOENN(GOLEM),
    SPECIES_TO_HOENN(NOSEPASS),
    SPECIES_TO_HOENN(SKITTY),
    SPECIES_TO_HOENN(DELCATTY),
    SPECIES_TO_HOENN(ZUBAT),
    SPECIES_TO_HOENN(GOLBAT),
    SPECIES_TO_HOENN(CROBAT),
    SPECIES_TO_HOENN(TENTACOOL),
    SPECIES_TO_HOENN(TENTACRUEL),
    SPECIES_TO_HOENN(SABLEYE),
    SPECIES_TO_HOENN(MAWILE),
    SPECIES_TO_HOENN(ARON),
    SPECIES_TO_HOENN(LAIRON),
    SPECIES_TO_HOENN(AGGRON),
    SPECIES_TO_HOENN(MACHOP),
    SPECIES_TO_HOENN(MACHOKE),
    SPECIES_TO_HOENN(MACHAMP),
    SPECIES_TO_HOENN(MEDITITE),
    SPECIES_TO_HOENN(MEDICHAM),
    SPECIES_TO_HOENN(ELECTRIKE),
    SPECIES_TO_HOENN(MANECTRIC),
    SPECIES_TO_HOENN(PLUSLE),
    SPECIES_TO_HOENN(MINUN),
    SPECIES_TO_HOENN(MAGNEMITE),
    SPECIES_TO_HOENN(MAGNETON),
    SPECIES_TO_HOENN(VOLTORB),
    SPECIES_TO_HOENN(ELECTRODE),
    SPECIES_TO_HOENN(VOLBEAT),
    SPECIES_TO_HOENN(ILLUMISE),
    SPECIES_TO_HOENN(ODDISH),
    SPECIES_TO_HOENN(GLOOM),
    SPECIES_TO_HOENN(VILEPLUME),
    SPECIES_TO_HOENN(BELLOSSOM),
    SPECIES_TO_HOENN(DODUO),
    SPECIES_TO_HOENN(DODRIO),
    SPECIES_TO_HOENN(ROSELIA),
    SPECIES_TO_HOENN(GULPIN),
    SPECIES_TO_HOENN(SWALOT),
    SPECIES_TO_HOENN(CARVANHA),
    SPECIES_TO_HOENN(SHARPEDO),
    SPECIES_TO_HOENN(WAILMER),
    SPECIES_TO_HOENN(WAILORD),
    SPECIES_TO_HOENN(NUMEL),
    SPECIES_TO_HOENN(CAMERUPT),
    SPECIES_TO_HOENN(SLUGMA),
    SPECIES_TO_HOENN(MAGCARGO),
    SPECIES_TO_HOENN(TORKOAL),
    SPECIES_TO_HOENN(GRIMER),
    SPECIES_TO_HOENN(MUK),
    SPECIES_TO_HOENN(KOFFING),
    SPECIES_TO_HOENN(WEEZING),
    SPECIES_TO_HOENN(SPOINK),
    SPECIES_TO_HOENN(GRUMPIG),
    SPECIES_TO_HOENN(SANDSHREW),
    SPECIES_TO_HOENN(SANDSLASH),
    SPECIES_TO_HOENN(SPINDA),
    SPECIES_TO_HOENN(SKARMORY),
    SPECIES_TO_HOENN(TRAPINCH),
    SPECIES_TO_HOENN(VIBRAVA),
    SPECIES_TO_HOENN(FLYGON),
    SPECIES_TO_HOENN(CACNEA),
    SPECIES_TO_HOENN(CACTURNE),
    SPECIES_TO_HOENN(SWABLU),
    SPECIES_TO_HOENN(ALTARIA),
    SPECIES_TO_HOENN(ZANGOOSE),
    SPECIES_TO_HOENN(SEVIPER),
    SPECIES_TO_HOENN(LUNATONE),
    SPECIES_TO_HOENN(SOLROCK),
    SPECIES_TO_HOENN(BARBOACH),
    SPECIES_TO_HOENN(WHISCASH),
    SPECIES_TO_HOENN(CORPHISH),
    SPECIES_TO_HOENN(CRAWDAUNT),
    SPECIES_TO_HOENN(BALTOY),
    SPECIES_TO_HOENN(CLAYDOL),
    SPECIES_TO_HOENN(LILEEP),
    SPECIES_TO_HOENN(CRADILY),
    SPECIES_TO_HOENN(ANORITH),
    SPECIES_TO_HOENN(ARMALDO),
    SPECIES_TO_HOENN(IGGLYBUFF),
    SPECIES_TO_HOENN(JIGGLYPUFF),
    SPECIES_TO_HOENN(WIGGLYTUFF),
    SPECIES_TO_HOENN(FEEBAS),
    SPECIES_TO_HOENN(MILOTIC),
    SPECIES_TO_HOENN(CASTFORM),
    SPECIES_TO_HOENN(STARYU),
    SPECIES_TO_HOENN(STARMIE),
    SPECIES_TO_HOENN(KECLEON),
    SPECIES_TO_HOENN(SHUPPET),
    SPECIES_TO_HOENN(BANETTE),
    SPECIES_TO_HOENN(DUSKULL),
    SPECIES_TO_HOENN(DUSCLOPS),
    SPECIES_TO_HOENN(TROPIUS),
    SPECIES_TO_HOENN(CHIMECHO),
    SPECIES_TO_HOENN(ABSOL),
    SPECIES_TO_HOENN(VULPIX),
    SPECIES_TO_HOENN(NINETALES),
    SPECIES_TO_HOENN(PICHU),
    SPECIES_TO_HOENN(PIKACHU),
    SPECIES_TO_HOENN(RAICHU),
    SPECIES_TO_HOENN(PSYDUCK),
    SPECIES_TO_HOENN(GOLDUCK),
    SPECIES_TO_HOENN(WYNAUT),
    SPECIES_TO_HOENN(WOBBUFFET),
    SPECIES_TO_HOENN(NATU),
    SPECIES_TO_HOENN(XATU),
    SPECIES_TO_HOENN(GIRAFARIG),
    SPECIES_TO_HOENN(PHANPY),
    SPECIES_TO_HOENN(DONPHAN),
    SPECIES_TO_HOENN(PINSIR),
    SPECIES_TO_HOENN(HERACROSS),
    SPECIES_TO_HOENN(RHYHORN),
    SPECIES_TO_HOENN(RHYDON),
    SPECIES_TO_HOENN(SNORUNT),
    SPECIES_TO_HOENN(GLALIE),
    SPECIES_TO_HOENN(SPHEAL),
    SPECIES_TO_HOENN(SEALEO),
    SPECIES_TO_HOENN(WALREIN),
    SPECIES_TO_HOENN(CLAMPERL),
    SPECIES_TO_HOENN(HUNTAIL),
    SPECIES_TO_HOENN(GOREBYSS),
    SPECIES_TO_HOENN(RELICANTH),
    SPECIES_TO_HOENN(CORSOLA),
    SPECIES_TO_HOENN(CHINCHOU),
    SPECIES_TO_HOENN(LANTURN),
    SPECIES_TO_HOENN(LUVDISC),
    SPECIES_TO_HOENN(HORSEA),
    SPECIES_TO_HOENN(SEADRA),
    SPECIES_TO_HOENN(KINGDRA),
    SPECIES_TO_HOENN(BAGON),
    SPECIES_TO_HOENN(SHELGON),
    SPECIES_TO_HOENN(SALAMENCE),
    SPECIES_TO_HOENN(BELDUM),
    SPECIES_TO_HOENN(METANG),
    SPECIES_TO_HOENN(METAGROSS),
    SPECIES_TO_HOENN(REGIROCK),
    SPECIES_TO_HOENN(REGICE),
    SPECIES_TO_HOENN(REGISTEEL),
    SPECIES_TO_HOENN(LATIAS),
    SPECIES_TO_HOENN(LATIOS),
    SPECIES_TO_HOENN(KYOGRE),
    SPECIES_TO_HOENN(GROUDON),
    SPECIES_TO_HOENN(RAYQUAZA),
    SPECIES_TO_HOENN(JIRACHI),
    SPECIES_TO_HOENN(DEOXYS),
};

const u16 gSpeciesToNationalPokedexNum[NUM_SPECIES] = // Assigns all species to the National Dex Index (Summary No. for National Dex)
{
	SPECIES_TO_NATIONAL(BULBASAUR),
	SPECIES_TO_NATIONAL(IVYSAUR),
	SPECIES_TO_NATIONAL(VENUSAUR),
	SPECIES_TO_NATIONAL(CHARMANDER),
	SPECIES_TO_NATIONAL(CHARMELEON),
	SPECIES_TO_NATIONAL(CHARIZARD),
	SPECIES_TO_NATIONAL(SQUIRTLE),
	SPECIES_TO_NATIONAL(WARTORTLE),
	SPECIES_TO_NATIONAL(BLASTOISE),
	SPECIES_TO_NATIONAL(CATERPIE),
	SPECIES_TO_NATIONAL(METAPOD),
	SPECIES_TO_NATIONAL(BUTTERFREE),
	SPECIES_TO_NATIONAL(WEEDLE),
	SPECIES_TO_NATIONAL(KAKUNA),
	SPECIES_TO_NATIONAL(BEEDRILL),
	SPECIES_TO_NATIONAL(PIDGEY),
	SPECIES_TO_NATIONAL(PIDGEOTTO),
	SPECIES_TO_NATIONAL(PIDGEOT),
	SPECIES_TO_NATIONAL(RATTATA),
	SPECIES_TO_NATIONAL(RATICATE),
	SPECIES_TO_NATIONAL(SPEAROW),
	SPECIES_TO_NATIONAL(FEAROW),
	SPECIES_TO_NATIONAL(EKANS),
	SPECIES_TO_NATIONAL(ARBOK),
	SPECIES_TO_NATIONAL(PIKACHU),
	SPECIES_TO_NATIONAL(RAICHU),
	SPECIES_TO_NATIONAL(SANDSHREW),
	SPECIES_TO_NATIONAL(SANDSLASH),
	SPECIES_TO_NATIONAL(NIDORAN_F),
	SPECIES_TO_NATIONAL(NIDORINA),
	SPECIES_TO_NATIONAL(NIDOQUEEN),
	SPECIES_TO_NATIONAL(NIDORAN_M),
	SPECIES_TO_NATIONAL(NIDORINO),
	SPECIES_TO_NATIONAL(NIDOKING),
	SPECIES_TO_NATIONAL(CLEFAIRY),
	SPECIES_TO_NATIONAL(CLEFABLE),
	SPECIES_TO_NATIONAL(VULPIX),
	SPECIES_TO_NATIONAL(NINETALES),
	SPECIES_TO_NATIONAL(JIGGLYPUFF),
	SPECIES_TO_NATIONAL(WIGGLYTUFF),
	SPECIES_TO_NATIONAL(ZUBAT),
	SPECIES_TO_NATIONAL(GOLBAT),
	SPECIES_TO_NATIONAL(ODDISH),
	SPECIES_TO_NATIONAL(GLOOM),
	SPECIES_TO_NATIONAL(VILEPLUME),
	SPECIES_TO_NATIONAL(PARAS),
	SPECIES_TO_NATIONAL(PARASECT),
	SPECIES_TO_NATIONAL(VENONAT),
	SPECIES_TO_NATIONAL(VENOMOTH),
	SPECIES_TO_NATIONAL(DIGLETT),
	SPECIES_TO_NATIONAL(DUGTRIO),
	SPECIES_TO_NATIONAL(MEOWTH),
	SPECIES_TO_NATIONAL(PERSIAN),
	SPECIES_TO_NATIONAL(PSYDUCK),
	SPECIES_TO_NATIONAL(GOLDUCK),
	SPECIES_TO_NATIONAL(MANKEY),
	SPECIES_TO_NATIONAL(PRIMEAPE),
	SPECIES_TO_NATIONAL(GROWLITHE),
	SPECIES_TO_NATIONAL(ARCANINE),
	SPECIES_TO_NATIONAL(POLIWAG),
	SPECIES_TO_NATIONAL(POLIWHIRL),
	SPECIES_TO_NATIONAL(POLIWRATH),
	SPECIES_TO_NATIONAL(ABRA),
	SPECIES_TO_NATIONAL(KADABRA),
	SPECIES_TO_NATIONAL(ALAKAZAM),
	SPECIES_TO_NATIONAL(MACHOP),
	SPECIES_TO_NATIONAL(MACHOKE),
	SPECIES_TO_NATIONAL(MACHAMP),
	SPECIES_TO_NATIONAL(BELLSPROUT),
	SPECIES_TO_NATIONAL(WEEPINBELL),
	SPECIES_TO_NATIONAL(VICTREEBEL),
	SPECIES_TO_NATIONAL(TENTACOOL),
	SPECIES_TO_NATIONAL(TENTACRUEL),
	SPECIES_TO_NATIONAL(GEODUDE),
	SPECIES_TO_NATIONAL(GRAVELER),
	SPECIES_TO_NATIONAL(GOLEM),
	SPECIES_TO_NATIONAL(PONYTA),
	SPECIES_TO_NATIONAL(RAPIDASH),
	SPECIES_TO_NATIONAL(SLOWPOKE),
	SPECIES_TO_NATIONAL(SLOWBRO),
	SPECIES_TO_NATIONAL(MAGNEMITE),
	SPECIES_TO_NATIONAL(MAGNETON),
	SPECIES_TO_NATIONAL(FARFETCHD),
	SPECIES_TO_NATIONAL(DODUO),
	SPECIES_TO_NATIONAL(DODRIO),
	SPECIES_TO_NATIONAL(SEEL),
	SPECIES_TO_NATIONAL(DEWGONG),
	SPECIES_TO_NATIONAL(GRIMER),
	SPECIES_TO_NATIONAL(MUK),
	SPECIES_TO_NATIONAL(SHELLDER),
	SPECIES_TO_NATIONAL(CLOYSTER),
	SPECIES_TO_NATIONAL(GASTLY),
	SPECIES_TO_NATIONAL(HAUNTER),
	SPECIES_TO_NATIONAL(GENGAR),
	SPECIES_TO_NATIONAL(ONIX),
	SPECIES_TO_NATIONAL(DROWZEE),
	SPECIES_TO_NATIONAL(HYPNO),
	SPECIES_TO_NATIONAL(KRABBY),
	SPECIES_TO_NATIONAL(KINGLER),
	SPECIES_TO_NATIONAL(VOLTORB),
	SPECIES_TO_NATIONAL(ELECTRODE),
	SPECIES_TO_NATIONAL(EXEGGCUTE),
	SPECIES_TO_NATIONAL(EXEGGUTOR),
	SPECIES_TO_NATIONAL(CUBONE),
	SPECIES_TO_NATIONAL(MAROWAK),
	SPECIES_TO_NATIONAL(HITMONLEE),
	SPECIES_TO_NATIONAL(HITMONCHAN),
	SPECIES_TO_NATIONAL(LICKITUNG),
	SPECIES_TO_NATIONAL(KOFFING),
	SPECIES_TO_NATIONAL(WEEZING),
	SPECIES_TO_NATIONAL(RHYHORN),
	SPECIES_TO_NATIONAL(RHYDON),
	SPECIES_TO_NATIONAL(CHANSEY),
	SPECIES_TO_NATIONAL(TANGELA),
	SPECIES_TO_NATIONAL(KANGASKHAN),
	SPECIES_TO_NATIONAL(HORSEA),
	SPECIES_TO_NATIONAL(SEADRA),
	SPECIES_TO_NATIONAL(GOLDEEN),
	SPECIES_TO_NATIONAL(SEAKING),
	SPECIES_TO_NATIONAL(STARYU),
	SPECIES_TO_NATIONAL(STARMIE),
	SPECIES_TO_NATIONAL(MR_MIME),
	SPECIES_TO_NATIONAL(SCYTHER),
	SPECIES_TO_NATIONAL(JYNX),
	SPECIES_TO_NATIONAL(ELECTABUZZ),
	SPECIES_TO_NATIONAL(MAGMAR),
	SPECIES_TO_NATIONAL(PINSIR),
	SPECIES_TO_NATIONAL(TAUROS),
	SPECIES_TO_NATIONAL(MAGIKARP),
	SPECIES_TO_NATIONAL(GYARADOS),
	SPECIES_TO_NATIONAL(LAPRAS),
	SPECIES_TO_NATIONAL(DITTO),
	SPECIES_TO_NATIONAL(EEVEE),
	SPECIES_TO_NATIONAL(VAPOREON),
	SPECIES_TO_NATIONAL(JOLTEON),
	SPECIES_TO_NATIONAL(FLAREON),
	SPECIES_TO_NATIONAL(PORYGON),
	SPECIES_TO_NATIONAL(OMANYTE),
	SPECIES_TO_NATIONAL(OMASTAR),
	SPECIES_TO_NATIONAL(KABUTO),
	SPECIES_TO_NATIONAL(KABUTOPS),
	SPECIES_TO_NATIONAL(AERODACTYL),
	SPECIES_TO_NATIONAL(SNORLAX),
	SPECIES_TO_NATIONAL(ARTICUNO),
	SPECIES_TO_NATIONAL(ZAPDOS),
	SPECIES_TO_NATIONAL(MOLTRES),
	SPECIES_TO_NATIONAL(DRATINI),
	SPECIES_TO_NATIONAL(DRAGONAIR),
	SPECIES_TO_NATIONAL(DRAGONITE),
	SPECIES_TO_NATIONAL(MEWTWO),
	SPECIES_TO_NATIONAL(MEW),
	SPECIES_TO_NATIONAL(CHIKORITA),
	SPECIES_TO_NATIONAL(BAYLEEF),
	SPECIES_TO_NATIONAL(MEGANIUM),
	SPECIES_TO_NATIONAL(CYNDAQUIL),
	SPECIES_TO_NATIONAL(QUILAVA),
	SPECIES_TO_NATIONAL(TYPHLOSION),
	SPECIES_TO_NATIONAL(TOTODILE),
	SPECIES_TO_NATIONAL(CROCONAW),
	SPECIES_TO_NATIONAL(FERALIGATR),
	SPECIES_TO_NATIONAL(SENTRET),
	SPECIES_TO_NATIONAL(FURRET),
	SPECIES_TO_NATIONAL(HOOTHOOT),
	SPECIES_TO_NATIONAL(NOCTOWL),
	SPECIES_TO_NATIONAL(LEDYBA),
	SPECIES_TO_NATIONAL(LEDIAN),
	SPECIES_TO_NATIONAL(SPINARAK),
	SPECIES_TO_NATIONAL(ARIADOS),
	SPECIES_TO_NATIONAL(CROBAT),
	SPECIES_TO_NATIONAL(CHINCHOU),
	SPECIES_TO_NATIONAL(LANTURN),
	SPECIES_TO_NATIONAL(PICHU),
	SPECIES_TO_NATIONAL(CLEFFA),
	SPECIES_TO_NATIONAL(IGGLYBUFF),
	SPECIES_TO_NATIONAL(TOGEPI),
	SPECIES_TO_NATIONAL(TOGETIC),
	SPECIES_TO_NATIONAL(NATU),
	SPECIES_TO_NATIONAL(XATU),
	SPECIES_TO_NATIONAL(MAREEP),
	SPECIES_TO_NATIONAL(FLAAFFY),
	SPECIES_TO_NATIONAL(AMPHAROS),
	SPECIES_TO_NATIONAL(BELLOSSOM),
	SPECIES_TO_NATIONAL(MARILL),
	SPECIES_TO_NATIONAL(AZUMARILL),
	SPECIES_TO_NATIONAL(SUDOWOODO),
	SPECIES_TO_NATIONAL(POLITOED),
	SPECIES_TO_NATIONAL(HOPPIP),
	SPECIES_TO_NATIONAL(SKIPLOOM),
	SPECIES_TO_NATIONAL(JUMPLUFF),
	SPECIES_TO_NATIONAL(AIPOM),
	SPECIES_TO_NATIONAL(SUNKERN),
	SPECIES_TO_NATIONAL(SUNFLORA),
	SPECIES_TO_NATIONAL(YANMA),
	SPECIES_TO_NATIONAL(WOOPER),
	SPECIES_TO_NATIONAL(QUAGSIRE),
	SPECIES_TO_NATIONAL(ESPEON),
	SPECIES_TO_NATIONAL(UMBREON),
	SPECIES_TO_NATIONAL(MURKROW),
	SPECIES_TO_NATIONAL(SLOWKING),
	SPECIES_TO_NATIONAL(MISDREAVUS),
	SPECIES_TO_NATIONAL(UNOWN),
	SPECIES_TO_NATIONAL(WOBBUFFET),
	SPECIES_TO_NATIONAL(GIRAFARIG),
	SPECIES_TO_NATIONAL(PINECO),
	SPECIES_TO_NATIONAL(FORRETRESS),
	SPECIES_TO_NATIONAL(DUNSPARCE),
	SPECIES_TO_NATIONAL(GLIGAR),
	SPECIES_TO_NATIONAL(STEELIX),
	SPECIES_TO_NATIONAL(SNUBBULL),
	SPECIES_TO_NATIONAL(GRANBULL),
	SPECIES_TO_NATIONAL(QWILFISH),
	SPECIES_TO_NATIONAL(SCIZOR),
	SPECIES_TO_NATIONAL(SHUCKLE),
	SPECIES_TO_NATIONAL(HERACROSS),
	SPECIES_TO_NATIONAL(SNEASEL),
	SPECIES_TO_NATIONAL(TEDDIURSA),
	SPECIES_TO_NATIONAL(URSARING),
	SPECIES_TO_NATIONAL(SLUGMA),
	SPECIES_TO_NATIONAL(MAGCARGO),
	SPECIES_TO_NATIONAL(SWINUB),
	SPECIES_TO_NATIONAL(PILOSWINE),
	SPECIES_TO_NATIONAL(CORSOLA),
	SPECIES_TO_NATIONAL(REMORAID),
	SPECIES_TO_NATIONAL(OCTILLERY),
	SPECIES_TO_NATIONAL(DELIBIRD),
	SPECIES_TO_NATIONAL(MANTINE),
	SPECIES_TO_NATIONAL(SKARMORY),
	SPECIES_TO_NATIONAL(HOUNDOUR),
	SPECIES_TO_NATIONAL(HOUNDOOM),
	SPECIES_TO_NATIONAL(KINGDRA),
	SPECIES_TO_NATIONAL(PHANPY),
	SPECIES_TO_NATIONAL(DONPHAN),
	SPECIES_TO_NATIONAL(PORYGON2),
	SPECIES_TO_NATIONAL(STANTLER),
	SPECIES_TO_NATIONAL(SMEARGLE),
	SPECIES_TO_NATIONAL(TYROGUE),
	SPECIES_TO_NATIONAL(HITMONTOP),
	SPECIES_TO_NATIONAL(SMOOCHUM),
	SPECIES_TO_NATIONAL(ELEKID),
	SPECIES_TO_NATIONAL(MAGBY),
	SPECIES_TO_NATIONAL(MILTANK),
	SPECIES_TO_NATIONAL(BLISSEY),
	SPECIES_TO_NATIONAL(RAIKOU),
	SPECIES_TO_NATIONAL(ENTEI),
	SPECIES_TO_NATIONAL(SUICUNE),
	SPECIES_TO_NATIONAL(LARVITAR),
	SPECIES_TO_NATIONAL(PUPITAR),
	SPECIES_TO_NATIONAL(TYRANITAR),
	SPECIES_TO_NATIONAL(LUGIA),
	SPECIES_TO_NATIONAL(HO_OH),
	SPECIES_TO_NATIONAL(CELEBI),
	SPECIES_TO_NATIONAL(TREECKO),
	SPECIES_TO_NATIONAL(GROVYLE),
	SPECIES_TO_NATIONAL(SCEPTILE),
	SPECIES_TO_NATIONAL(TORCHIC),
	SPECIES_TO_NATIONAL(COMBUSKEN),
	SPECIES_TO_NATIONAL(BLAZIKEN),
	SPECIES_TO_NATIONAL(MUDKIP),
	SPECIES_TO_NATIONAL(MARSHTOMP),
	SPECIES_TO_NATIONAL(SWAMPERT),
	SPECIES_TO_NATIONAL(POOCHYENA),
	SPECIES_TO_NATIONAL(MIGHTYENA),
	SPECIES_TO_NATIONAL(ZIGZAGOON),
	SPECIES_TO_NATIONAL(LINOONE),
	SPECIES_TO_NATIONAL(WURMPLE),
	SPECIES_TO_NATIONAL(SILCOON),
	SPECIES_TO_NATIONAL(BEAUTIFLY),
	SPECIES_TO_NATIONAL(CASCOON),
	SPECIES_TO_NATIONAL(DUSTOX),
	SPECIES_TO_NATIONAL(LOTAD),
	SPECIES_TO_NATIONAL(LOMBRE),
	SPECIES_TO_NATIONAL(LUDICOLO),
	SPECIES_TO_NATIONAL(SEEDOT),
	SPECIES_TO_NATIONAL(NUZLEAF),
	SPECIES_TO_NATIONAL(SHIFTRY),
	SPECIES_TO_NATIONAL(TAILLOW),
	SPECIES_TO_NATIONAL(SWELLOW),
	SPECIES_TO_NATIONAL(WINGULL),
	SPECIES_TO_NATIONAL(PELIPPER),
	SPECIES_TO_NATIONAL(RALTS),
	SPECIES_TO_NATIONAL(KIRLIA),
	SPECIES_TO_NATIONAL(GARDEVOIR),
	SPECIES_TO_NATIONAL(SURSKIT),
	SPECIES_TO_NATIONAL(MASQUERAIN),
	SPECIES_TO_NATIONAL(SHROOMISH),
	SPECIES_TO_NATIONAL(BRELOOM),
	SPECIES_TO_NATIONAL(SLAKOTH),
	SPECIES_TO_NATIONAL(VIGOROTH),
	SPECIES_TO_NATIONAL(SLAKING),
	SPECIES_TO_NATIONAL(NINCADA),
	SPECIES_TO_NATIONAL(NINJASK),
	SPECIES_TO_NATIONAL(SHEDINJA),
	SPECIES_TO_NATIONAL(WHISMUR),
	SPECIES_TO_NATIONAL(LOUDRED),
	SPECIES_TO_NATIONAL(EXPLOUD),
	SPECIES_TO_NATIONAL(MAKUHITA),
	SPECIES_TO_NATIONAL(HARIYAMA),
	SPECIES_TO_NATIONAL(AZURILL),
	SPECIES_TO_NATIONAL(NOSEPASS),
	SPECIES_TO_NATIONAL(SKITTY),
	SPECIES_TO_NATIONAL(DELCATTY),
	SPECIES_TO_NATIONAL(SABLEYE),
	SPECIES_TO_NATIONAL(MAWILE),
	SPECIES_TO_NATIONAL(ARON),
	SPECIES_TO_NATIONAL(LAIRON),
	SPECIES_TO_NATIONAL(AGGRON),
	SPECIES_TO_NATIONAL(MEDITITE),
	SPECIES_TO_NATIONAL(MEDICHAM),
	SPECIES_TO_NATIONAL(ELECTRIKE),
	SPECIES_TO_NATIONAL(MANECTRIC),
	SPECIES_TO_NATIONAL(PLUSLE),
	SPECIES_TO_NATIONAL(MINUN),
	SPECIES_TO_NATIONAL(VOLBEAT),
	SPECIES_TO_NATIONAL(ILLUMISE),
	SPECIES_TO_NATIONAL(ROSELIA),
	SPECIES_TO_NATIONAL(GULPIN),
	SPECIES_TO_NATIONAL(SWALOT),
	SPECIES_TO_NATIONAL(CARVANHA),
	SPECIES_TO_NATIONAL(SHARPEDO),
	SPECIES_TO_NATIONAL(WAILMER),
	SPECIES_TO_NATIONAL(WAILORD),
	SPECIES_TO_NATIONAL(NUMEL),
	SPECIES_TO_NATIONAL(CAMERUPT),
	SPECIES_TO_NATIONAL(TORKOAL),
	SPECIES_TO_NATIONAL(SPOINK),
	SPECIES_TO_NATIONAL(GRUMPIG),
	SPECIES_TO_NATIONAL(SPINDA),
	SPECIES_TO_NATIONAL(TRAPINCH),
	SPECIES_TO_NATIONAL(VIBRAVA),
	SPECIES_TO_NATIONAL(FLYGON),
	SPECIES_TO_NATIONAL(CACNEA),
	SPECIES_TO_NATIONAL(CACTURNE),
	SPECIES_TO_NATIONAL(SWABLU),
	SPECIES_TO_NATIONAL(ALTARIA),
	SPECIES_TO_NATIONAL(ZANGOOSE),
	SPECIES_TO_NATIONAL(SEVIPER),
	SPECIES_TO_NATIONAL(LUNATONE),
	SPECIES_TO_NATIONAL(SOLROCK),
	SPECIES_TO_NATIONAL(BARBOACH),
	SPECIES_TO_NATIONAL(WHISCASH),
	SPECIES_TO_NATIONAL(CORPHISH),
	SPECIES_TO_NATIONAL(CRAWDAUNT),
	SPECIES_TO_NATIONAL(BALTOY),
	SPECIES_TO_NATIONAL(CLAYDOL),
	SPECIES_TO_NATIONAL(LILEEP),
	SPECIES_TO_NATIONAL(CRADILY),
	SPECIES_TO_NATIONAL(ANORITH),
	SPECIES_TO_NATIONAL(ARMALDO),
	SPECIES_TO_NATIONAL(FEEBAS),
	SPECIES_TO_NATIONAL(MILOTIC),
	SPECIES_TO_NATIONAL(CASTFORM),
	SPECIES_TO_NATIONAL(KECLEON),
	SPECIES_TO_NATIONAL(SHUPPET),
	SPECIES_TO_NATIONAL(BANETTE),
	SPECIES_TO_NATIONAL(DUSKULL),
	SPECIES_TO_NATIONAL(DUSCLOPS),
	SPECIES_TO_NATIONAL(TROPIUS),
	SPECIES_TO_NATIONAL(CHIMECHO),
	SPECIES_TO_NATIONAL(ABSOL),
	SPECIES_TO_NATIONAL(WYNAUT),
	SPECIES_TO_NATIONAL(SNORUNT),
	SPECIES_TO_NATIONAL(GLALIE),
	SPECIES_TO_NATIONAL(SPHEAL),
	SPECIES_TO_NATIONAL(SEALEO),
	SPECIES_TO_NATIONAL(WALREIN),
	SPECIES_TO_NATIONAL(CLAMPERL),
	SPECIES_TO_NATIONAL(HUNTAIL),
	SPECIES_TO_NATIONAL(GOREBYSS),
	SPECIES_TO_NATIONAL(RELICANTH),
	SPECIES_TO_NATIONAL(LUVDISC),
	SPECIES_TO_NATIONAL(BAGON),
	SPECIES_TO_NATIONAL(SHELGON),
	SPECIES_TO_NATIONAL(SALAMENCE),
	SPECIES_TO_NATIONAL(BELDUM),
	SPECIES_TO_NATIONAL(METANG),
	SPECIES_TO_NATIONAL(METAGROSS),
	SPECIES_TO_NATIONAL(REGIROCK),
	SPECIES_TO_NATIONAL(REGICE),
	SPECIES_TO_NATIONAL(REGISTEEL),
	SPECIES_TO_NATIONAL(LATIAS),
	SPECIES_TO_NATIONAL(LATIOS),
	SPECIES_TO_NATIONAL(KYOGRE),
	SPECIES_TO_NATIONAL(GROUDON),
	SPECIES_TO_NATIONAL(RAYQUAZA),
	SPECIES_TO_NATIONAL(JIRACHI),
	SPECIES_TO_NATIONAL(DEOXYS),
	SPECIES_TO_NATIONAL(TURTWIG),
	SPECIES_TO_NATIONAL(GROTLE),
	SPECIES_TO_NATIONAL(TORTERRA),
	SPECIES_TO_NATIONAL(CHIMCHAR),
	SPECIES_TO_NATIONAL(MONFERNO),
	SPECIES_TO_NATIONAL(INFERNAPE),
	SPECIES_TO_NATIONAL(PIPLUP),
	SPECIES_TO_NATIONAL(PRINPLUP),
	SPECIES_TO_NATIONAL(EMPOLEON),
	SPECIES_TO_NATIONAL(STARLY),
	SPECIES_TO_NATIONAL(STARAVIA),
	SPECIES_TO_NATIONAL(STARAPTOR),
	SPECIES_TO_NATIONAL(BIDOOF),
	SPECIES_TO_NATIONAL(BIBAREL),
	SPECIES_TO_NATIONAL(KRICKETOT),
	SPECIES_TO_NATIONAL(KRICKETUNE),
	SPECIES_TO_NATIONAL(SHINX),
	SPECIES_TO_NATIONAL(LUXIO),
	SPECIES_TO_NATIONAL(LUXRAY),
	SPECIES_TO_NATIONAL(BUDEW),
	SPECIES_TO_NATIONAL(ROSERADE),
	SPECIES_TO_NATIONAL(CRANIDOS),
	SPECIES_TO_NATIONAL(RAMPARDOS),
	SPECIES_TO_NATIONAL(SHIELDON),
	SPECIES_TO_NATIONAL(BASTIODON),
	SPECIES_TO_NATIONAL(BURMY),
	SPECIES_TO_NATIONAL(WORMADAM),
	SPECIES_TO_NATIONAL(MOTHIM),
	SPECIES_TO_NATIONAL(COMBEE),
	SPECIES_TO_NATIONAL(VESPIQUEN),
	SPECIES_TO_NATIONAL(PACHIRISU),
	SPECIES_TO_NATIONAL(BUIZEL),
	SPECIES_TO_NATIONAL(FLOATZEL),
	SPECIES_TO_NATIONAL(CHERUBI),
	SPECIES_TO_NATIONAL(CHERRIM),
	SPECIES_TO_NATIONAL(SHELLOS),
	SPECIES_TO_NATIONAL(GASTRODON),
	SPECIES_TO_NATIONAL(AMBIPOM),
	SPECIES_TO_NATIONAL(DRIFLOON),
	SPECIES_TO_NATIONAL(DRIFBLIM),
	SPECIES_TO_NATIONAL(BUNEARY),
	SPECIES_TO_NATIONAL(LOPUNNY),
	SPECIES_TO_NATIONAL(MISMAGIUS),
	SPECIES_TO_NATIONAL(HONCHKROW),
	SPECIES_TO_NATIONAL(GLAMEOW),
	SPECIES_TO_NATIONAL(PURUGLY),
	SPECIES_TO_NATIONAL(CHINGLING),
	SPECIES_TO_NATIONAL(STUNKY),
	SPECIES_TO_NATIONAL(SKUNTANK),
	SPECIES_TO_NATIONAL(BRONZOR),
	SPECIES_TO_NATIONAL(BRONZONG),
	SPECIES_TO_NATIONAL(BONSLY),
	SPECIES_TO_NATIONAL(MIMEJR),
	SPECIES_TO_NATIONAL(HAPPINY),
	SPECIES_TO_NATIONAL(CHATOT),
	SPECIES_TO_NATIONAL(SPIRITOMB),
	SPECIES_TO_NATIONAL(GIBLE),
	SPECIES_TO_NATIONAL(GABITE),
	SPECIES_TO_NATIONAL(GARCHOMP),
	SPECIES_TO_NATIONAL(MUNCHLAX),
	SPECIES_TO_NATIONAL(RIOLU),
	SPECIES_TO_NATIONAL(LUCARIO),
	SPECIES_TO_NATIONAL(HIPPOPOTAS),
	SPECIES_TO_NATIONAL(HIPPOWDON),
	SPECIES_TO_NATIONAL(SKORUPI),
	SPECIES_TO_NATIONAL(DRAPION),
	SPECIES_TO_NATIONAL(CROAGUNK),
	SPECIES_TO_NATIONAL(TOXICROAK),
	SPECIES_TO_NATIONAL(CARNIVINE),
	SPECIES_TO_NATIONAL(FINNEON),
	SPECIES_TO_NATIONAL(LUMINEON),
	SPECIES_TO_NATIONAL(MANTYKE),
	SPECIES_TO_NATIONAL(SNOVER),
	SPECIES_TO_NATIONAL(ABOMASNOW),
	SPECIES_TO_NATIONAL(WEAVILE),
	SPECIES_TO_NATIONAL(MAGNEZONE),
	SPECIES_TO_NATIONAL(LICKILICKY),
	SPECIES_TO_NATIONAL(RHYPERIOR),
	SPECIES_TO_NATIONAL(TANGROWTH),
	SPECIES_TO_NATIONAL(ELECTIVIRE),
	SPECIES_TO_NATIONAL(MAGMORTAR),
	SPECIES_TO_NATIONAL(TOGEKISS),
	SPECIES_TO_NATIONAL(YANMEGA),
	SPECIES_TO_NATIONAL(LEAFEON),
	SPECIES_TO_NATIONAL(GLACEON),
	SPECIES_TO_NATIONAL(GLISCOR),
	SPECIES_TO_NATIONAL(MAMOSWINE),
	SPECIES_TO_NATIONAL(PORYGON_Z),
	SPECIES_TO_NATIONAL(GALLADE),
	SPECIES_TO_NATIONAL(PROBOPASS),
	SPECIES_TO_NATIONAL(DUSKNOIR),
	SPECIES_TO_NATIONAL(FROSLASS),
	SPECIES_TO_NATIONAL(ROTOM),
	SPECIES_TO_NATIONAL(UXIE),
	SPECIES_TO_NATIONAL(MESPRIT),
	SPECIES_TO_NATIONAL(AZELF),
	SPECIES_TO_NATIONAL(DIALGA),
	SPECIES_TO_NATIONAL(PALKIA),
	SPECIES_TO_NATIONAL(HEATRAN),
	SPECIES_TO_NATIONAL(REGIGIGAS),
	SPECIES_TO_NATIONAL(GIRATINA),
	SPECIES_TO_NATIONAL(CRESSELIA),
	SPECIES_TO_NATIONAL(PHIONE),
	SPECIES_TO_NATIONAL(MANAPHY),
	SPECIES_TO_NATIONAL(DARKRAI),
	SPECIES_TO_NATIONAL(SHAYMIN),
	SPECIES_TO_NATIONAL(ARCEUS),
	SPECIES_TO_NATIONAL(VICTINI),
	SPECIES_TO_NATIONAL(SNIVY),
	SPECIES_TO_NATIONAL(SERVINE),
	SPECIES_TO_NATIONAL(SERPERIOR),
	SPECIES_TO_NATIONAL(TEPIG),
	SPECIES_TO_NATIONAL(PIGNITE),
	SPECIES_TO_NATIONAL(EMBOAR),
	SPECIES_TO_NATIONAL(OSHAWOTT),
	SPECIES_TO_NATIONAL(DEWOTT),
	SPECIES_TO_NATIONAL(SAMUROTT),
	SPECIES_TO_NATIONAL(PATRAT),
	SPECIES_TO_NATIONAL(WATCHOG),
	SPECIES_TO_NATIONAL(LILLIPUP),
	SPECIES_TO_NATIONAL(HERDIER),
	SPECIES_TO_NATIONAL(STOUTLAND),
	SPECIES_TO_NATIONAL(PURRLOIN),
	SPECIES_TO_NATIONAL(LIEPARD),
	SPECIES_TO_NATIONAL(PANSAGE),
	SPECIES_TO_NATIONAL(SIMISAGE),
	SPECIES_TO_NATIONAL(PANSEAR),
	SPECIES_TO_NATIONAL(SIMISEAR),
	SPECIES_TO_NATIONAL(PANPOUR),
	SPECIES_TO_NATIONAL(SIMIPOUR),
	SPECIES_TO_NATIONAL(MUNNA),
	SPECIES_TO_NATIONAL(MUSHARNA),
	SPECIES_TO_NATIONAL(PIDOVE),
	SPECIES_TO_NATIONAL(TRANQUILL),
	SPECIES_TO_NATIONAL(UNFEZANT),
	SPECIES_TO_NATIONAL(BLITZLE),
	SPECIES_TO_NATIONAL(ZEBSTRIKA),
	SPECIES_TO_NATIONAL(ROGGENROLA),
	SPECIES_TO_NATIONAL(BOLDORE),
	SPECIES_TO_NATIONAL(GIGALITH),
	SPECIES_TO_NATIONAL(WOOBAT),
	SPECIES_TO_NATIONAL(SWOOBAT),
	SPECIES_TO_NATIONAL(DRILBUR),
	SPECIES_TO_NATIONAL(EXCADRILL),
	SPECIES_TO_NATIONAL(AUDINO),
	SPECIES_TO_NATIONAL(TIMBURR),
	SPECIES_TO_NATIONAL(GURDURR),
	SPECIES_TO_NATIONAL(CONKELDURR),
	SPECIES_TO_NATIONAL(TYMPOLE),
	SPECIES_TO_NATIONAL(PALPITOAD),
	SPECIES_TO_NATIONAL(SEISMITOAD),
	SPECIES_TO_NATIONAL(THROH),
	SPECIES_TO_NATIONAL(SAWK),
	SPECIES_TO_NATIONAL(SEWADDLE),
	SPECIES_TO_NATIONAL(SWADLOON),
	SPECIES_TO_NATIONAL(LEAVANNY),
	SPECIES_TO_NATIONAL(VENIPEDE),
	SPECIES_TO_NATIONAL(WHIRLIPEDE),
	SPECIES_TO_NATIONAL(SCOLIPEDE),
	SPECIES_TO_NATIONAL(COTTONEE),
	SPECIES_TO_NATIONAL(WHIMSICOTT),
	SPECIES_TO_NATIONAL(PETILIL),
	SPECIES_TO_NATIONAL(LILLIGANT),
	SPECIES_TO_NATIONAL(BASCULIN),
	SPECIES_TO_NATIONAL(SANDILE),
	SPECIES_TO_NATIONAL(KROKOROK),
	SPECIES_TO_NATIONAL(KROOKODILE),
	SPECIES_TO_NATIONAL(DARUMAKA),
	SPECIES_TO_NATIONAL(DARMANITAN),
	SPECIES_TO_NATIONAL(MARACTUS),
	SPECIES_TO_NATIONAL(DWEBBLE),
	SPECIES_TO_NATIONAL(CRUSTLE),
	SPECIES_TO_NATIONAL(SCRAGGY),
	SPECIES_TO_NATIONAL(SCRAFTY),
	SPECIES_TO_NATIONAL(SIGILYPH),
	SPECIES_TO_NATIONAL(YAMASK),
	SPECIES_TO_NATIONAL(COFAGRIGUS),
	SPECIES_TO_NATIONAL(TIRTOUGA),
	SPECIES_TO_NATIONAL(CARRACOSTA),
	SPECIES_TO_NATIONAL(ARCHEN),
	SPECIES_TO_NATIONAL(ARCHEOPS),
	SPECIES_TO_NATIONAL(TRUBBISH),
	SPECIES_TO_NATIONAL(GARBODOR),
	SPECIES_TO_NATIONAL(ZORUA),
	SPECIES_TO_NATIONAL(ZOROARK),
	SPECIES_TO_NATIONAL(MINCCINO),
	SPECIES_TO_NATIONAL(CINCCINO),
	SPECIES_TO_NATIONAL(GOTHITA),
	SPECIES_TO_NATIONAL(GOTHORITA),
	SPECIES_TO_NATIONAL(GOTHITELLE),
	SPECIES_TO_NATIONAL(SOLOSIS),
	SPECIES_TO_NATIONAL(DUOSION),
	SPECIES_TO_NATIONAL(REUNICLUS),
	SPECIES_TO_NATIONAL(DUCKLETT),
	SPECIES_TO_NATIONAL(SWANNA),
	SPECIES_TO_NATIONAL(VANILLITE),
	SPECIES_TO_NATIONAL(VANILLISH),
	SPECIES_TO_NATIONAL(VANILLUXE),
	SPECIES_TO_NATIONAL(DEERLING),
	SPECIES_TO_NATIONAL(SAWSBUCK),
	SPECIES_TO_NATIONAL(EMOLGA),
	SPECIES_TO_NATIONAL(KARRABLAST),
	SPECIES_TO_NATIONAL(ESCAVALIER),
	SPECIES_TO_NATIONAL(FOONGUS),
	SPECIES_TO_NATIONAL(AMOONGUSS),
	SPECIES_TO_NATIONAL(FRILLISH),
	SPECIES_TO_NATIONAL(JELLICENT),
	SPECIES_TO_NATIONAL(ALOMOMOLA),
	SPECIES_TO_NATIONAL(JOLTIK),
	SPECIES_TO_NATIONAL(GALVANTULA),
	SPECIES_TO_NATIONAL(FERROSEED),
	SPECIES_TO_NATIONAL(FERROTHORN),
	SPECIES_TO_NATIONAL(KLINK),
	SPECIES_TO_NATIONAL(KLANG),
	SPECIES_TO_NATIONAL(KLINKLANG),
	SPECIES_TO_NATIONAL(TYNAMO),
	SPECIES_TO_NATIONAL(EELEKTRIK),
	SPECIES_TO_NATIONAL(EELEKTROSS),
	SPECIES_TO_NATIONAL(ELGYEM),
	SPECIES_TO_NATIONAL(BEHEEYEM),
	SPECIES_TO_NATIONAL(LITWICK),
	SPECIES_TO_NATIONAL(LAMPENT),
	SPECIES_TO_NATIONAL(CHANDELURE),
	SPECIES_TO_NATIONAL(AXEW),
	SPECIES_TO_NATIONAL(FRAXURE),
	SPECIES_TO_NATIONAL(HAXORUS),
	SPECIES_TO_NATIONAL(CUBCHOO),
	SPECIES_TO_NATIONAL(BEARTIC),
	SPECIES_TO_NATIONAL(CRYOGONAL),
	SPECIES_TO_NATIONAL(SHELMET),
	SPECIES_TO_NATIONAL(ACCELGOR),
	SPECIES_TO_NATIONAL(STUNFISK),
	SPECIES_TO_NATIONAL(MIENFOO),
	SPECIES_TO_NATIONAL(MIENSHAO),
	SPECIES_TO_NATIONAL(DRUDDIGON),
	SPECIES_TO_NATIONAL(GOLETT),
	SPECIES_TO_NATIONAL(GOLURK),
	SPECIES_TO_NATIONAL(PAWNIARD),
	SPECIES_TO_NATIONAL(BISHARP),
	SPECIES_TO_NATIONAL(BOUFFALANT),
	SPECIES_TO_NATIONAL(RUFFLET),
	SPECIES_TO_NATIONAL(BRAVIARY),
	SPECIES_TO_NATIONAL(VULLABY),
	SPECIES_TO_NATIONAL(MANDIBUZZ),
	SPECIES_TO_NATIONAL(HEATMOR),
	SPECIES_TO_NATIONAL(DURANT),
	SPECIES_TO_NATIONAL(DEINO),
	SPECIES_TO_NATIONAL(ZWEILOUS),
	SPECIES_TO_NATIONAL(HYDREIGON),
	SPECIES_TO_NATIONAL(LARVESTA),
	SPECIES_TO_NATIONAL(VOLCARONA),
	SPECIES_TO_NATIONAL(COBALION),
	SPECIES_TO_NATIONAL(TERRAKION),
	SPECIES_TO_NATIONAL(VIRIZION),
	SPECIES_TO_NATIONAL(TORNADUS),
	SPECIES_TO_NATIONAL(THUNDURUS),
	SPECIES_TO_NATIONAL(RESHIRAM),
	SPECIES_TO_NATIONAL(ZEKROM),
	SPECIES_TO_NATIONAL(LANDORUS),
	SPECIES_TO_NATIONAL(KYUREM),
	SPECIES_TO_NATIONAL(KELDEO),
	SPECIES_TO_NATIONAL(MELOETTA),
	SPECIES_TO_NATIONAL(GENESECT),
	SPECIES_TO_NATIONAL(CHESPIN),
	SPECIES_TO_NATIONAL(QUILLADIN),
	SPECIES_TO_NATIONAL(CHESNAUGHT),
	SPECIES_TO_NATIONAL(FENNEKIN),
	SPECIES_TO_NATIONAL(BRAIXEN),
	SPECIES_TO_NATIONAL(DELPHOX),
	SPECIES_TO_NATIONAL(FROAKIE),
	SPECIES_TO_NATIONAL(FROGADIER),
	SPECIES_TO_NATIONAL(GRENINJA),
	SPECIES_TO_NATIONAL(BUNNELBY),
	SPECIES_TO_NATIONAL(DIGGERSBY),
	SPECIES_TO_NATIONAL(FLETCHLING),
	SPECIES_TO_NATIONAL(FLETCHINDER),
	SPECIES_TO_NATIONAL(TALONFLAME),
	SPECIES_TO_NATIONAL(SCATTERBUG),
	SPECIES_TO_NATIONAL(SPEWPA),
	SPECIES_TO_NATIONAL(VIVILLON),
	SPECIES_TO_NATIONAL(LITLEO),
	SPECIES_TO_NATIONAL(PYROAR),
	SPECIES_TO_NATIONAL(FLABEBE),
	SPECIES_TO_NATIONAL(FLOETTE),
	SPECIES_TO_NATIONAL(FLORGES),
	SPECIES_TO_NATIONAL(SKIDDO),
	SPECIES_TO_NATIONAL(GOGOAT),
	SPECIES_TO_NATIONAL(PANCHAM),
	SPECIES_TO_NATIONAL(PANGORO),
	SPECIES_TO_NATIONAL(FURFROU),
	SPECIES_TO_NATIONAL(ESPURR),
	SPECIES_TO_NATIONAL(MEOWSTIC),
	SPECIES_TO_NATIONAL(HONEDGE),
	SPECIES_TO_NATIONAL(DOUBLADE),
	SPECIES_TO_NATIONAL(AEGISLASH),
	SPECIES_TO_NATIONAL(SPRITZEE),
	SPECIES_TO_NATIONAL(AROMATISSE),
	SPECIES_TO_NATIONAL(SWIRLIX),
	SPECIES_TO_NATIONAL(SLURPUFF),
	SPECIES_TO_NATIONAL(INKAY),
	SPECIES_TO_NATIONAL(MALAMAR),
	SPECIES_TO_NATIONAL(BINACLE),
	SPECIES_TO_NATIONAL(BARBARACLE),
	SPECIES_TO_NATIONAL(SKRELP),
	SPECIES_TO_NATIONAL(DRAGALGE),
	SPECIES_TO_NATIONAL(CLAUNCHER),
	SPECIES_TO_NATIONAL(CLAWITZER),
	SPECIES_TO_NATIONAL(HELIOPTILE),
	SPECIES_TO_NATIONAL(HELIOLISK),
	SPECIES_TO_NATIONAL(TYRUNT),
	SPECIES_TO_NATIONAL(TYRANTRUM),
	SPECIES_TO_NATIONAL(AMAURA),
	SPECIES_TO_NATIONAL(AURORUS),
	SPECIES_TO_NATIONAL(SYLVEON),
	SPECIES_TO_NATIONAL(HAWLUCHA),
	SPECIES_TO_NATIONAL(DEDENNE),
	SPECIES_TO_NATIONAL(CARBINK),
	SPECIES_TO_NATIONAL(GOOMY),
	SPECIES_TO_NATIONAL(SLIGGOO),
	SPECIES_TO_NATIONAL(GOODRA),
	SPECIES_TO_NATIONAL(KLEFKI),
	SPECIES_TO_NATIONAL(PHANTUMP),
	SPECIES_TO_NATIONAL(TREVENANT),
	SPECIES_TO_NATIONAL(PUMPKABOO),
	SPECIES_TO_NATIONAL(GOURGEIST),
	SPECIES_TO_NATIONAL(BERGMITE),
	SPECIES_TO_NATIONAL(AVALUGG),
	SPECIES_TO_NATIONAL(NOIBAT),
	SPECIES_TO_NATIONAL(NOIVERN),
	SPECIES_TO_NATIONAL(XERNEAS),
	SPECIES_TO_NATIONAL(YVELTAL),
	SPECIES_TO_NATIONAL(ZYGARDE),
	SPECIES_TO_NATIONAL(DIANCIE),
	SPECIES_TO_NATIONAL(HOOPA),
	SPECIES_TO_NATIONAL(VOLCANION),
	SPECIES_TO_NATIONAL(ROWLET),
	SPECIES_TO_NATIONAL(DARTRIX),
	SPECIES_TO_NATIONAL(DECIDUEYE),
	SPECIES_TO_NATIONAL(LITTEN),
	SPECIES_TO_NATIONAL(TORRACAT),
	SPECIES_TO_NATIONAL(INCINEROAR),
	SPECIES_TO_NATIONAL(POPPLIO),
	SPECIES_TO_NATIONAL(BRIONNE),
	SPECIES_TO_NATIONAL(PRIMARINA),
	SPECIES_TO_NATIONAL(PIKIPEK),
	SPECIES_TO_NATIONAL(TRUMBEAK),
	SPECIES_TO_NATIONAL(TOUCANNON),
	SPECIES_TO_NATIONAL(YUNGOOS),
	SPECIES_TO_NATIONAL(GUMSHOOS),
	SPECIES_TO_NATIONAL(GRUBBIN),
	SPECIES_TO_NATIONAL(CHARJABUG),
	SPECIES_TO_NATIONAL(VIKAVOLT),
	SPECIES_TO_NATIONAL(CRABRAWLER),
	SPECIES_TO_NATIONAL(CRABOMINABLE),
	SPECIES_TO_NATIONAL(ORICORIO),
	SPECIES_TO_NATIONAL(CUTIEFLY),
	SPECIES_TO_NATIONAL(RIBOMBEE),
	SPECIES_TO_NATIONAL(ROCKRUFF),
	SPECIES_TO_NATIONAL(LYCANROC),
	SPECIES_TO_NATIONAL(WISHIWASHI),
	SPECIES_TO_NATIONAL(MAREANIE),
	SPECIES_TO_NATIONAL(TOXAPEX),
	SPECIES_TO_NATIONAL(MUDBRAY),
	SPECIES_TO_NATIONAL(MUDSDALE),
	SPECIES_TO_NATIONAL(DEWPIDER),
	SPECIES_TO_NATIONAL(ARAQUANID),
	SPECIES_TO_NATIONAL(FOMANTIS),
	SPECIES_TO_NATIONAL(LURANTIS),
	SPECIES_TO_NATIONAL(MORELULL),
	SPECIES_TO_NATIONAL(SHIINOTIC),
	SPECIES_TO_NATIONAL(SALANDIT),
	SPECIES_TO_NATIONAL(SALAZZLE),
	SPECIES_TO_NATIONAL(STUFFUL),
	SPECIES_TO_NATIONAL(BEWEAR),
	SPECIES_TO_NATIONAL(BOUNSWEET),
	SPECIES_TO_NATIONAL(STEENEE),
	SPECIES_TO_NATIONAL(TSAREENA),
	SPECIES_TO_NATIONAL(COMFEY),
	SPECIES_TO_NATIONAL(ORANGURU),
	SPECIES_TO_NATIONAL(PASSIMIAN),
	SPECIES_TO_NATIONAL(WIMPOD),
	SPECIES_TO_NATIONAL(GOLISOPOD),
	SPECIES_TO_NATIONAL(SANDYGAST),
	SPECIES_TO_NATIONAL(PALOSSAND),
	SPECIES_TO_NATIONAL(PYUKUMUKU),
	SPECIES_TO_NATIONAL(TYPE_NULL),
	SPECIES_TO_NATIONAL(SILVALLY),
	SPECIES_TO_NATIONAL(MINIOR),
	SPECIES_TO_NATIONAL(KOMALA),
	SPECIES_TO_NATIONAL(TURTONATOR),
	SPECIES_TO_NATIONAL(TOGEDEMARU),
	SPECIES_TO_NATIONAL(MIMIKYU),
	SPECIES_TO_NATIONAL(BRUXISH),
	SPECIES_TO_NATIONAL(DRAMPA),
	SPECIES_TO_NATIONAL(DHELMISE),
	SPECIES_TO_NATIONAL(JANGMO_O),
	SPECIES_TO_NATIONAL(HAKAMO_O),
	SPECIES_TO_NATIONAL(KOMMO_O),
	SPECIES_TO_NATIONAL(TAPU_KOKO),
	SPECIES_TO_NATIONAL(TAPU_LELE),
	SPECIES_TO_NATIONAL(TAPU_BULU),
	SPECIES_TO_NATIONAL(TAPU_FINI),
	SPECIES_TO_NATIONAL(COSMOG),
	SPECIES_TO_NATIONAL(COSMOEM),
	SPECIES_TO_NATIONAL(SOLGALEO),
	SPECIES_TO_NATIONAL(LUNALA),
	SPECIES_TO_NATIONAL(NIHILEGO),
	SPECIES_TO_NATIONAL(BUZZWOLE),
	SPECIES_TO_NATIONAL(PHEROMOSA),
	SPECIES_TO_NATIONAL(XURKITREE),
	SPECIES_TO_NATIONAL(CELESTEELA),
	SPECIES_TO_NATIONAL(KARTANA),
	SPECIES_TO_NATIONAL(GUZZLORD),
	SPECIES_TO_NATIONAL(NECROZMA),
	SPECIES_TO_NATIONAL(MAGEARNA),
	SPECIES_TO_NATIONAL(MARSHADOW),
	SPECIES_TO_NATIONAL(POIPOLE),
	SPECIES_TO_NATIONAL(NAGANADEL),
	SPECIES_TO_NATIONAL(STAKATAKA),
	SPECIES_TO_NATIONAL(BLACEPHALON),
	SPECIES_TO_NATIONAL(ZERAORA),
};

const u16 gHoennToNationalOrder[HOENN_DEX_COUNT] = // Assigns Hoenn Dex Pokémon (Using National Dex Index)
{
    HOENN_TO_NATIONAL(TREECKO),
    HOENN_TO_NATIONAL(GROVYLE),
    HOENN_TO_NATIONAL(SCEPTILE),
    HOENN_TO_NATIONAL(TORCHIC),
    HOENN_TO_NATIONAL(COMBUSKEN),
    HOENN_TO_NATIONAL(BLAZIKEN),
    HOENN_TO_NATIONAL(MUDKIP),
    HOENN_TO_NATIONAL(MARSHTOMP),
    HOENN_TO_NATIONAL(SWAMPERT),
    HOENN_TO_NATIONAL(POOCHYENA),
    HOENN_TO_NATIONAL(MIGHTYENA),
    HOENN_TO_NATIONAL(ZIGZAGOON),
    HOENN_TO_NATIONAL(LINOONE),
    HOENN_TO_NATIONAL(WURMPLE),
    HOENN_TO_NATIONAL(SILCOON),
    HOENN_TO_NATIONAL(BEAUTIFLY),
    HOENN_TO_NATIONAL(CASCOON),
    HOENN_TO_NATIONAL(DUSTOX),
    HOENN_TO_NATIONAL(LOTAD),
    HOENN_TO_NATIONAL(LOMBRE),
    HOENN_TO_NATIONAL(LUDICOLO),
    HOENN_TO_NATIONAL(SEEDOT),
    HOENN_TO_NATIONAL(NUZLEAF),
    HOENN_TO_NATIONAL(SHIFTRY),
    HOENN_TO_NATIONAL(TAILLOW),
    HOENN_TO_NATIONAL(SWELLOW),
    HOENN_TO_NATIONAL(WINGULL),
    HOENN_TO_NATIONAL(PELIPPER),
    HOENN_TO_NATIONAL(RALTS),
    HOENN_TO_NATIONAL(KIRLIA),
    HOENN_TO_NATIONAL(GARDEVOIR),
    HOENN_TO_NATIONAL(SURSKIT),
    HOENN_TO_NATIONAL(MASQUERAIN),
    HOENN_TO_NATIONAL(SHROOMISH),
    HOENN_TO_NATIONAL(BRELOOM),
    HOENN_TO_NATIONAL(SLAKOTH),
    HOENN_TO_NATIONAL(VIGOROTH),
    HOENN_TO_NATIONAL(SLAKING),
    HOENN_TO_NATIONAL(ABRA),
    HOENN_TO_NATIONAL(KADABRA),
    HOENN_TO_NATIONAL(ALAKAZAM),
    HOENN_TO_NATIONAL(NINCADA),
    HOENN_TO_NATIONAL(NINJASK),
    HOENN_TO_NATIONAL(SHEDINJA),
    HOENN_TO_NATIONAL(WHISMUR),
    HOENN_TO_NATIONAL(LOUDRED),
    HOENN_TO_NATIONAL(EXPLOUD),
    HOENN_TO_NATIONAL(MAKUHITA),
    HOENN_TO_NATIONAL(HARIYAMA),
    HOENN_TO_NATIONAL(GOLDEEN),
    HOENN_TO_NATIONAL(SEAKING),
    HOENN_TO_NATIONAL(MAGIKARP),
    HOENN_TO_NATIONAL(GYARADOS),
    HOENN_TO_NATIONAL(AZURILL),
    HOENN_TO_NATIONAL(MARILL),
    HOENN_TO_NATIONAL(AZUMARILL),
    HOENN_TO_NATIONAL(GEODUDE),
    HOENN_TO_NATIONAL(GRAVELER),
    HOENN_TO_NATIONAL(GOLEM),
    HOENN_TO_NATIONAL(NOSEPASS),
    HOENN_TO_NATIONAL(SKITTY),
    HOENN_TO_NATIONAL(DELCATTY),
    HOENN_TO_NATIONAL(ZUBAT),
    HOENN_TO_NATIONAL(GOLBAT),
    HOENN_TO_NATIONAL(CROBAT),
    HOENN_TO_NATIONAL(TENTACOOL),
    HOENN_TO_NATIONAL(TENTACRUEL),
    HOENN_TO_NATIONAL(SABLEYE),
    HOENN_TO_NATIONAL(MAWILE),
    HOENN_TO_NATIONAL(ARON),
    HOENN_TO_NATIONAL(LAIRON),
    HOENN_TO_NATIONAL(AGGRON),
    HOENN_TO_NATIONAL(MACHOP),
    HOENN_TO_NATIONAL(MACHOKE),
    HOENN_TO_NATIONAL(MACHAMP),
    HOENN_TO_NATIONAL(MEDITITE),
    HOENN_TO_NATIONAL(MEDICHAM),
    HOENN_TO_NATIONAL(ELECTRIKE),
    HOENN_TO_NATIONAL(MANECTRIC),
    HOENN_TO_NATIONAL(PLUSLE),
    HOENN_TO_NATIONAL(MINUN),
    HOENN_TO_NATIONAL(MAGNEMITE),
    HOENN_TO_NATIONAL(MAGNETON),
    HOENN_TO_NATIONAL(VOLTORB),
    HOENN_TO_NATIONAL(ELECTRODE),
    HOENN_TO_NATIONAL(VOLBEAT),
    HOENN_TO_NATIONAL(ILLUMISE),
    HOENN_TO_NATIONAL(ODDISH),
    HOENN_TO_NATIONAL(GLOOM),
    HOENN_TO_NATIONAL(VILEPLUME),
    HOENN_TO_NATIONAL(BELLOSSOM),
    HOENN_TO_NATIONAL(DODUO),
    HOENN_TO_NATIONAL(DODRIO),
    HOENN_TO_NATIONAL(ROSELIA),
    HOENN_TO_NATIONAL(GULPIN),
    HOENN_TO_NATIONAL(SWALOT),
    HOENN_TO_NATIONAL(CARVANHA),
    HOENN_TO_NATIONAL(SHARPEDO),
    HOENN_TO_NATIONAL(WAILMER),
    HOENN_TO_NATIONAL(WAILORD),
    HOENN_TO_NATIONAL(NUMEL),
    HOENN_TO_NATIONAL(CAMERUPT),
    HOENN_TO_NATIONAL(SLUGMA),
    HOENN_TO_NATIONAL(MAGCARGO),
    HOENN_TO_NATIONAL(TORKOAL),
    HOENN_TO_NATIONAL(GRIMER),
    HOENN_TO_NATIONAL(MUK),
    HOENN_TO_NATIONAL(KOFFING),
    HOENN_TO_NATIONAL(WEEZING),
    HOENN_TO_NATIONAL(SPOINK),
    HOENN_TO_NATIONAL(GRUMPIG),
    HOENN_TO_NATIONAL(SANDSHREW),
    HOENN_TO_NATIONAL(SANDSLASH),
    HOENN_TO_NATIONAL(SPINDA),
    HOENN_TO_NATIONAL(SKARMORY),
    HOENN_TO_NATIONAL(TRAPINCH),
    HOENN_TO_NATIONAL(VIBRAVA),
    HOENN_TO_NATIONAL(FLYGON),
    HOENN_TO_NATIONAL(CACNEA),
    HOENN_TO_NATIONAL(CACTURNE),
    HOENN_TO_NATIONAL(SWABLU),
    HOENN_TO_NATIONAL(ALTARIA),
    HOENN_TO_NATIONAL(ZANGOOSE),
    HOENN_TO_NATIONAL(SEVIPER),
    HOENN_TO_NATIONAL(LUNATONE),
    HOENN_TO_NATIONAL(SOLROCK),
    HOENN_TO_NATIONAL(BARBOACH),
    HOENN_TO_NATIONAL(WHISCASH),
    HOENN_TO_NATIONAL(CORPHISH),
    HOENN_TO_NATIONAL(CRAWDAUNT),
    HOENN_TO_NATIONAL(BALTOY),
    HOENN_TO_NATIONAL(CLAYDOL),
    HOENN_TO_NATIONAL(LILEEP),
    HOENN_TO_NATIONAL(CRADILY),
    HOENN_TO_NATIONAL(ANORITH),
    HOENN_TO_NATIONAL(ARMALDO),
    HOENN_TO_NATIONAL(IGGLYBUFF),
    HOENN_TO_NATIONAL(JIGGLYPUFF),
    HOENN_TO_NATIONAL(WIGGLYTUFF),
    HOENN_TO_NATIONAL(FEEBAS),
    HOENN_TO_NATIONAL(MILOTIC),
    HOENN_TO_NATIONAL(CASTFORM),
    HOENN_TO_NATIONAL(STARYU),
    HOENN_TO_NATIONAL(STARMIE),
    HOENN_TO_NATIONAL(KECLEON),
    HOENN_TO_NATIONAL(SHUPPET),
    HOENN_TO_NATIONAL(BANETTE),
    HOENN_TO_NATIONAL(DUSKULL),
    HOENN_TO_NATIONAL(DUSCLOPS),
    HOENN_TO_NATIONAL(TROPIUS),
    HOENN_TO_NATIONAL(CHIMECHO),
    HOENN_TO_NATIONAL(ABSOL),
    HOENN_TO_NATIONAL(VULPIX),
    HOENN_TO_NATIONAL(NINETALES),
    HOENN_TO_NATIONAL(PICHU),
    HOENN_TO_NATIONAL(PIKACHU),
    HOENN_TO_NATIONAL(RAICHU),
    HOENN_TO_NATIONAL(PSYDUCK),
    HOENN_TO_NATIONAL(GOLDUCK),
    HOENN_TO_NATIONAL(WYNAUT),
    HOENN_TO_NATIONAL(WOBBUFFET),
    HOENN_TO_NATIONAL(NATU),
    HOENN_TO_NATIONAL(XATU),
    HOENN_TO_NATIONAL(GIRAFARIG),
    HOENN_TO_NATIONAL(PHANPY),
    HOENN_TO_NATIONAL(DONPHAN),
    HOENN_TO_NATIONAL(PINSIR),
    HOENN_TO_NATIONAL(HERACROSS),
    HOENN_TO_NATIONAL(RHYHORN),
    HOENN_TO_NATIONAL(RHYDON),
    HOENN_TO_NATIONAL(SNORUNT),
    HOENN_TO_NATIONAL(GLALIE),
    HOENN_TO_NATIONAL(SPHEAL),
    HOENN_TO_NATIONAL(SEALEO),
    HOENN_TO_NATIONAL(WALREIN),
    HOENN_TO_NATIONAL(CLAMPERL),
    HOENN_TO_NATIONAL(HUNTAIL),
    HOENN_TO_NATIONAL(GOREBYSS),
    HOENN_TO_NATIONAL(RELICANTH),
    HOENN_TO_NATIONAL(CORSOLA),
    HOENN_TO_NATIONAL(CHINCHOU),
    HOENN_TO_NATIONAL(LANTURN),
    HOENN_TO_NATIONAL(LUVDISC),
    HOENN_TO_NATIONAL(HORSEA),
    HOENN_TO_NATIONAL(SEADRA),
    HOENN_TO_NATIONAL(KINGDRA),
    HOENN_TO_NATIONAL(BAGON),
    HOENN_TO_NATIONAL(SHELGON),
    HOENN_TO_NATIONAL(SALAMENCE),
    HOENN_TO_NATIONAL(BELDUM),
    HOENN_TO_NATIONAL(METANG),
    HOENN_TO_NATIONAL(METAGROSS),
    HOENN_TO_NATIONAL(REGIROCK),
    HOENN_TO_NATIONAL(REGICE),
    HOENN_TO_NATIONAL(REGISTEEL),
    HOENN_TO_NATIONAL(LATIAS),
    HOENN_TO_NATIONAL(LATIOS),
    HOENN_TO_NATIONAL(KYOGRE),
    HOENN_TO_NATIONAL(GROUDON),
    HOENN_TO_NATIONAL(RAYQUAZA),
    HOENN_TO_NATIONAL(JIRACHI),
    HOENN_TO_NATIONAL(DEOXYS),
};

const struct SpindaSpot gSpindaSpotGraphics[] =
{
    {16, 14, INCBIN_U16("graphics/spinda_spots/spot_0.bin")},
    {40, 15, INCBIN_U16("graphics/spinda_spots/spot_1.bin")},
    {22, 32, INCBIN_U16("graphics/spinda_spots/spot_2.bin")},
    {34, 33, INCBIN_U16("graphics/spinda_spots/spot_3.bin")}
};

#include "data/pokemon/item_effects.h"

const s8 gNatureStatTable[][5] =
{
    // Atk Def Spd Sp.Atk Sp.Def
    {    0,  0,  0,     0,     0}, // Hardy
    {   +1, -1,  0,     0,     0}, // Lonely
    {   +1,  0, -1,     0,     0}, // Brave
    {   +1,  0,  0,    -1,     0}, // Adamant
    {   +1,  0,  0,     0,    -1}, // Naughty
    {   -1, +1,  0,     0,     0}, // Bold
    {    0,  0,  0,     0,     0}, // Docile
    {    0, +1, -1,     0,     0}, // Relaxed
    {    0, +1,  0,    -1,     0}, // Impish
    {    0, +1,  0,     0,    -1}, // Lax
    {   -1,  0, +1,     0,     0}, // Timid
    {    0, -1, +1,     0,     0}, // Hasty
    {    0,  0,  0,     0,     0}, // Serious
    {    0,  0, +1,    -1,     0}, // Jolly
    {    0,  0, +1,     0,    -1}, // Naive
    {   -1,  0,  0,    +1,     0}, // Modest
    {    0, -1,  0,    +1,     0}, // Mild
    {    0,  0, -1,    +1,     0}, // Quiet
    {    0,  0,  0,     0,     0}, // Bashful
    {    0,  0,  0,    +1,    -1}, // Rash
    {   -1,  0,  0,     0,    +1}, // Calm
    {    0, -1,  0,     0,    +1}, // Gentle
    {    0,  0, -1,     0,    +1}, // Sassy
    {    0,  0,  0,    -1,    +1}, // Careful
    {    0,  0,  0,     0,     0} // Quirky
};

#include "data/pokemon/tmhm_learnsets.h"
#include "data/pokemon/trainer_class_lookups.h"
#include "data/pokemon/cry_ids.h"
#include "data/pokemon/experience_tables.h"
#include "data/pokemon/base_stats.h"
#include "data/pokemon/level_up_learnsets.h"
#include "data/pokemon/evolution.h"
#include "data/pokemon/level_up_learnset_pointers.h"

void ZeroBoxMonData(struct BoxPokemon *boxMon)
{
    u8 *raw = (u8 *)boxMon;
    u32 i;
    for (i = 0; i < sizeof(struct BoxPokemon); i++)
        raw[i] = 0;
}

void ZeroMonData(struct Pokemon *mon)
{
    u32 arg;
    ZeroBoxMonData(&mon->box);
    arg = 0;
    SetMonData(mon, MON_DATA_STATUS, &arg);
    SetMonData(mon, MON_DATA_LEVEL, &arg);
    SetMonData(mon, MON_DATA_HP, &arg);
    SetMonData(mon, MON_DATA_MAX_HP, &arg);
    SetMonData(mon, MON_DATA_ATK, &arg);
    SetMonData(mon, MON_DATA_DEF, &arg);
    SetMonData(mon, MON_DATA_SPEED, &arg);
    SetMonData(mon, MON_DATA_SPATK, &arg);
    SetMonData(mon, MON_DATA_SPDEF, &arg);
    arg = 255;
    SetMonData(mon, MON_DATA_MAIL, &arg);
}

void ZeroPlayerPartyMons(void)
{
    s32 i;
    for (i = 0; i < 6; i++)
        ZeroMonData(&gPlayerParty[i]);
}

void ZeroEnemyPartyMons(void)
{
    s32 i;
    for (i = 0; i < 6; i++)
        ZeroMonData(&gEnemyParty[i]);
}

void CreateMon(struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 hasFixedPersonality, u32 fixedPersonality, u8 otIdType, u32 fixedOtId)
{
    u32 arg;

    ZeroMonData(mon);
    CreateBoxMon(&mon->box, species, level, fixedIV, hasFixedPersonality, fixedPersonality, otIdType, fixedOtId);
    SetMonData(mon, MON_DATA_LEVEL, &level);
    arg = 255;
    SetMonData(mon, MON_DATA_MAIL, &arg);
    CalculateMonStats(mon);
}

void CreateBoxMon(struct BoxPokemon *boxMon, u16 species, u8 level, u8 fixedIV, u8 hasFixedPersonality, u32 fixedPersonality, u8 otIdType, u32 fixedOtId)
{
    u8 speciesName[POKEMON_NAME_LENGTH + 1];
    u32 personality;
    u32 value;
    u16 checksum;

    ZeroBoxMonData(boxMon);

    if (hasFixedPersonality)
        personality = fixedPersonality;
    else
        personality = Random32();

    SetBoxMonData(boxMon, MON_DATA_PERSONALITY, &personality);

    //Determine original trainer ID
    if (otIdType == 2) //Pokemon cannot be shiny
    {
        u32 shinyValue;
        do
        {
            value = Random32();
            shinyValue = HIHALF(value) ^ LOHALF(value) ^ HIHALF(personality) ^ LOHALF(personality);
        } while (shinyValue < 8);
    }
    else if (otIdType == 1) //Pokemon has a preset OT ID
    {
        value = fixedOtId;
    }
    else //Player is the OT
    {
        value = gSaveBlock2.playerTrainerId[0]
              | (gSaveBlock2.playerTrainerId[1] << 8)
              | (gSaveBlock2.playerTrainerId[2] << 16)
              | (gSaveBlock2.playerTrainerId[3] << 24);
    }

    SetBoxMonData(boxMon, MON_DATA_OT_ID, &value);

    checksum = CalculateBoxMonChecksum(boxMon);
    SetBoxMonData(boxMon, MON_DATA_CHECKSUM, &checksum);
    EncryptBoxMon(boxMon);
    GetSpeciesName(speciesName, species);
    SetBoxMonData(boxMon, MON_DATA_NICKNAME, speciesName);
    SetBoxMonData(boxMon, MON_DATA_LANGUAGE, &gGameLanguage);
    SetBoxMonData(boxMon, MON_DATA_OT_NAME, gSaveBlock2.playerName);
    SetBoxMonData(boxMon, MON_DATA_SPECIES, &species);
    SetBoxMonData(boxMon, MON_DATA_EXP, &gExperienceTables[gBaseStats[species].growthRate][level]);
    SetBoxMonData(boxMon, MON_DATA_FRIENDSHIP, &gBaseStats[species].friendship);
    value = sav1_map_get_name();
    SetBoxMonData(boxMon, MON_DATA_MET_LOCATION, &value);
    SetBoxMonData(boxMon, MON_DATA_MET_LEVEL, &level);
    SetBoxMonData(boxMon, MON_DATA_MET_GAME, &gGameVersion);
    value = 4;
    SetBoxMonData(boxMon, MON_DATA_POKEBALL, &value);
    SetBoxMonData(boxMon, MON_DATA_OT_GENDER, &gSaveBlock2.playerGender);

    if (fixedIV < 32)
    {
        SetBoxMonData(boxMon, MON_DATA_HP_IV, &fixedIV);
        SetBoxMonData(boxMon, MON_DATA_ATK_IV, &fixedIV);
        SetBoxMonData(boxMon, MON_DATA_DEF_IV, &fixedIV);
        SetBoxMonData(boxMon, MON_DATA_SPEED_IV, &fixedIV);
        SetBoxMonData(boxMon, MON_DATA_SPATK_IV, &fixedIV);
        SetBoxMonData(boxMon, MON_DATA_SPDEF_IV, &fixedIV);
    }
    else
    {
        u32 iv;
        value = Random();

        iv = value & 0x1F;
        SetBoxMonData(boxMon, MON_DATA_HP_IV, &iv);
        iv = (value & 0x3E0) >> 5;
        SetBoxMonData(boxMon, MON_DATA_ATK_IV, &iv);
        iv = (value & 0x7C00) >> 10;
        SetBoxMonData(boxMon, MON_DATA_DEF_IV, &iv);

        value = Random();

        iv = value & 0x1F;
        SetBoxMonData(boxMon, MON_DATA_SPEED_IV, &iv);
        iv = (value & 0x3E0) >> 5;
        SetBoxMonData(boxMon, MON_DATA_SPATK_IV, &iv);
        iv = (value & 0x7C00) >> 10;
        SetBoxMonData(boxMon, MON_DATA_SPDEF_IV, &iv);
    }

    if (gBaseStats[species].ability2)
    {
        value = personality & 1;
        SetBoxMonData(boxMon, MON_DATA_ALT_ABILITY, &value);
    }

    GiveBoxMonInitialMoveset(boxMon);
}

void CreateMonWithNature(struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 nature)
{
    u32 personality;

    do
    {
        personality = Random32();
    }
    while (nature != GetNatureFromPersonality(personality));

    CreateMon(mon, species, level, fixedIV, 1, personality, 0, 0);
}

void CreateMonWithGenderNatureLetter(struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 gender, u8 nature, u8 unownLetter)
{
    u32 personality;

    if ((u8)(unownLetter - 1) < 28)
    {
        u16 actualLetter;

        do
        {
            personality = Random32();
            actualLetter = ((((personality & 0x3000000) >> 18) | ((personality & 0x30000) >> 12) | ((personality & 0x300) >> 6) | (personality & 0x3)) % 28);
        }
        while (nature != GetNatureFromPersonality(personality)
            || gender != GetGenderFromSpeciesAndPersonality(species, personality)
            || actualLetter != unownLetter - 1);
    }
    else
    {
        do
        {
            personality = Random32();
        }
        while (nature != GetNatureFromPersonality(personality)
            || gender != GetGenderFromSpeciesAndPersonality(species, personality));
    }

    CreateMon(mon, species, level, fixedIV, 1, personality, 0, 0);
}

// This is only used to create Wally's Ralts.
void CreateMaleMon(struct Pokemon *mon, u16 species, u8 level)
{
    u32 personality;
    u32 otId;

    do
    {
        otId = Random32();
        personality = Random32();
    }
    while (GetGenderFromSpeciesAndPersonality(species, personality) != MON_MALE);
    CreateMon(mon, species, level, 32, 1, personality, 1, otId);
}

void CreateMonWithIVsPersonality(struct Pokemon *mon, u16 species, u8 level, u32 ivs, u32 personality)
{
    CreateMon(mon, species, level, 0, 1, personality, 0, 0);
    SetMonData(mon, MON_DATA_IVS, &ivs);
    CalculateMonStats(mon);
}

void CreateMonWithIVsOTID(struct Pokemon *mon, u16 species, u8 level, u8 *ivs, u32 otId)
{
    CreateMon(mon, species, level, 0, 0, 0, 1, otId);
    SetMonData(mon, MON_DATA_HP_IV, &ivs[0]);
    SetMonData(mon, MON_DATA_ATK_IV, &ivs[1]);
    SetMonData(mon, MON_DATA_DEF_IV, &ivs[2]);
    SetMonData(mon, MON_DATA_SPEED_IV, &ivs[3]);
    SetMonData(mon, MON_DATA_SPATK_IV, &ivs[4]);
    SetMonData(mon, MON_DATA_SPDEF_IV, &ivs[5]);
    CalculateMonStats(mon);
}

void CreateMonWithEVSpread(struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 evSpread)
{
    s32 i;
    s32 statCount = 0;
    u16 evAmount;
    u8 temp;

    CreateMon(mon, species, level, fixedIV, 0, 0, 0, 0);

    temp = evSpread;

    for (i = 0; i < 6; i++)
    {
        if (temp & 1)
            statCount++;
        temp >>= 1;
    }

    evAmount = 510 / statCount;

    temp = 1;

    for (i = 0; i < 6; i++)
    {
        if (evSpread & temp)
            SetMonData(mon, MON_DATA_HP_EV + i, &evAmount);
        temp <<= 1;
    }

    CalculateMonStats(mon);
}

/*void CreateMonWithFeature(struct Pokemon *mon, u16 species, u8 level, u8 fixedIV, u8 field, u16 value)
{
    CreateMon(mon, species, level, fixedIV, 0, 0, 0, 0);
    
    if (field < 90)
        SetMonData(mon, field, value);
    else
    {
        switch (field)
        {
            case 91: // make mon hidden ability and shiny
                
            case 90: // make mon shiny
                
                break;
        
        }
    }
    
}*/

void sub_803ADE8(struct Pokemon *mon, struct UnknownPokemonStruct *src)
{
    s32 i;
    u8 nickname[POKEMON_NAME_LENGTH + 1];
    u8 language;
    u8 value;

    CreateMon(mon, src->species, src->level, 0, 1, src->personality, 1, src->otId);

    for (i = 0; i < 4; i++)
        SetMonMoveSlot(mon, src->moves[i], i);

    SetMonData(mon, MON_DATA_PP_BONUSES, &src->ppBonuses);
    SetMonData(mon, MON_DATA_HELD_ITEM, &src->heldItem);

    StringCopy(nickname, src->nickname);

    if (nickname[0] == 0xFC && nickname[1] == 0x15)
        language = LANGUAGE_JAPANESE;
    else
        language = GAME_LANGUAGE;

    SetMonData(mon, MON_DATA_LANGUAGE, &language);
    Text_StripExtCtrlCodes(nickname);
    SetMonData(mon, MON_DATA_NICKNAME, nickname);
    SetMonData(mon, MON_DATA_FRIENDSHIP, &src->friendship);
    SetMonData(mon, MON_DATA_HP_EV, &src->hpEV);
    SetMonData(mon, MON_DATA_ATK_EV, &src->attackEV);
    SetMonData(mon, MON_DATA_DEF_EV, &src->defenseEV);
    SetMonData(mon, MON_DATA_SPEED_EV, &src->speedEV);
    SetMonData(mon, MON_DATA_SPATK_EV, &src->spAttackEV);
    SetMonData(mon, MON_DATA_SPDEF_EV, &src->spDefenseEV);
    value = src->altAbility;
    SetMonData(mon, MON_DATA_ALT_ABILITY, &value);
    value = src->hpIV;
    SetMonData(mon, MON_DATA_HP_IV, &value);
    value = src->attackIV;
    SetMonData(mon, MON_DATA_ATK_IV, &value);
    value = src->defenseIV;
    SetMonData(mon, MON_DATA_DEF_IV, &value);
    value = src->speedIV;
    SetMonData(mon, MON_DATA_SPEED_IV, &value);
    value = src->spAttackIV;
    SetMonData(mon, MON_DATA_SPATK_IV, &value);
    value = src->spDefenseIV;
    SetMonData(mon, MON_DATA_SPDEF_IV, &value);
    CalculateMonStats(mon);
}

void sub_803AF78(struct Pokemon *mon, struct UnknownPokemonStruct *dest)
{
    s32 i;
    u16 heldItem;

    dest->species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    heldItem = GetMonData(mon, MON_DATA_HELD_ITEM, NULL);

    if (heldItem == ITEM_ENIGMA_BERRY)
        heldItem = 0;

    dest->heldItem = heldItem;

    for (i = 0; i < 4; i++)
        dest->moves[i] = GetMonData(mon, MON_DATA_MOVE1 + i, NULL);

    dest->level = GetMonData(mon, MON_DATA_LEVEL, NULL);
    dest->ppBonuses = GetMonData(mon, MON_DATA_PP_BONUSES, NULL);
    dest->otId = GetMonData(mon, MON_DATA_OT_ID, NULL);
    dest->hpEV = GetMonData(mon, MON_DATA_HP_EV, NULL);
    dest->attackEV = GetMonData(mon, MON_DATA_ATK_EV, NULL);
    dest->defenseEV = GetMonData(mon, MON_DATA_DEF_EV, NULL);
    dest->speedEV = GetMonData(mon, MON_DATA_SPEED_EV, NULL);
    dest->spAttackEV = GetMonData(mon, MON_DATA_SPATK_EV, NULL);
    dest->spDefenseEV = GetMonData(mon, MON_DATA_SPDEF_EV, NULL);
    dest->friendship = GetMonData(mon, MON_DATA_FRIENDSHIP, NULL);
    dest->hpIV = GetMonData(mon, MON_DATA_HP_IV, NULL);
    dest->attackIV = GetMonData(mon, MON_DATA_ATK_IV, NULL);
    dest->defenseIV = GetMonData(mon, MON_DATA_DEF_IV, NULL);
    dest->speedIV  = GetMonData(mon, MON_DATA_SPEED_IV, NULL);
    dest->spAttackIV  = GetMonData(mon, MON_DATA_SPATK_IV, NULL);
    dest->spDefenseIV  = GetMonData(mon, MON_DATA_SPDEF_IV, NULL);
    dest->altAbility = GetMonData(mon, MON_DATA_ALT_ABILITY, NULL);
    dest->personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    GetMonData(mon, MON_DATA_NICKNAME, dest->nickname);
}

u16 CalculateBoxMonChecksum(struct BoxPokemon *boxMon)
{
    u16 checksum = 0;
    union PokemonSubstruct *substruct0 = GetSubstruct(boxMon, boxMon->personality, 0);
    union PokemonSubstruct *substruct1 = GetSubstruct(boxMon, boxMon->personality, 1);
    union PokemonSubstruct *substruct2 = GetSubstruct(boxMon, boxMon->personality, 2);
    union PokemonSubstruct *substruct3 = GetSubstruct(boxMon, boxMon->personality, 3);
    s32 i;

    for (i = 0; i < 6; i++)
        checksum += substruct0->raw[i];

    for (i = 0; i < 6; i++)
        checksum += substruct1->raw[i];

    for (i = 0; i < 6; i++)
        checksum += substruct2->raw[i];

    for (i = 0; i < 6; i++)
        checksum += substruct3->raw[i];

    return checksum;
}

#define CALC_STAT(base, iv, ev, statIndex, field)               \
{                                                               \
    u8 baseStat = gBaseStats[species].base;                     \
    s32 n = (((2 * baseStat + iv + ev / 4) * level) / 100) + 5; \
    u8 nature = GetNature(mon);                                 \
    n = nature_stat_mod(nature, n, statIndex);                  \
    SetMonData(mon, field, &n);                                 \
}

void CalculateMonStats(struct Pokemon *mon)
{
    s32 oldMaxHP = GetMonData(mon, MON_DATA_MAX_HP, NULL);
    s32 currentHP = GetMonData(mon, MON_DATA_HP, NULL);
    s32 hpIV = GetMonData(mon, MON_DATA_HP_IV, NULL);
    s32 hpEV = GetMonData(mon, MON_DATA_HP_EV, NULL);
    s32 attackIV = GetMonData(mon, MON_DATA_ATK_IV, NULL);
    s32 attackEV = GetMonData(mon, MON_DATA_ATK_EV, NULL);
    s32 defenseIV = GetMonData(mon, MON_DATA_DEF_IV, NULL);
    s32 defenseEV = GetMonData(mon, MON_DATA_DEF_EV, NULL);
    s32 speedIV = GetMonData(mon, MON_DATA_SPEED_IV, NULL);
    s32 speedEV = GetMonData(mon, MON_DATA_SPEED_EV, NULL);
    s32 spAttackIV = GetMonData(mon, MON_DATA_SPATK_IV, NULL);
    s32 spAttackEV = GetMonData(mon, MON_DATA_SPATK_EV, NULL);
    s32 spDefenseIV = GetMonData(mon, MON_DATA_SPDEF_IV, NULL);
    s32 spDefenseEV = GetMonData(mon, MON_DATA_SPDEF_EV, NULL);
    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    s32 level = GetLevelFromMonExp(mon);
    s32 newMaxHP;

    SetMonData(mon, MON_DATA_LEVEL, &level);

    if (species == SPECIES_SHEDINJA)
    {
        newMaxHP = 1;
    }
    else
    {
        s32 n = 2 * gBaseStats[species].baseHP + hpIV;
        newMaxHP = (((n + hpEV / 4) * level) / 100) + level + 10;
    }

    eStatHp = newMaxHP - oldMaxHP;
    if (eStatHp == 0)
        eStatHp = 1;

    SetMonData(mon, MON_DATA_MAX_HP, &newMaxHP);

    CALC_STAT(baseAttack, attackIV, attackEV, 1, MON_DATA_ATK)
    CALC_STAT(baseDefense, defenseIV, defenseEV, 2, MON_DATA_DEF)
    CALC_STAT(baseSpeed, speedIV, speedEV, 3, MON_DATA_SPEED)
    CALC_STAT(baseSpAttack, spAttackIV, spAttackEV, 4, MON_DATA_SPATK)
    CALC_STAT(baseSpDefense, spDefenseIV, spDefenseEV, 5, MON_DATA_SPDEF)

    if (species == SPECIES_SHEDINJA)
    {
        if (currentHP != 0 || oldMaxHP == 0)
            currentHP = 1;
        else
            return;
    }
    else
    {
        if (currentHP == 0 && oldMaxHP == 0)
            currentHP = newMaxHP;
        else if (currentHP != 0)
            currentHP += newMaxHP - oldMaxHP;
        else
            return;
    }

    SetMonData(mon, MON_DATA_HP, &currentHP);
}

#if DEBUG
void Nakamura_NakaGenderTest_RecalcStats(struct Pokemon *mon)
{
    s32 currentHP = GetMonData(mon, MON_DATA_HP, NULL);
    s32 hpIV = GetMonData(mon, MON_DATA_HP_IV, NULL);
    s32 hpEV = GetMonData(mon, MON_DATA_HP_EV, NULL);
    s32 attackIV = GetMonData(mon, MON_DATA_ATK_IV, NULL);
    s32 attackEV = GetMonData(mon, MON_DATA_ATK_EV, NULL);
    s32 defenseIV = GetMonData(mon, MON_DATA_DEF_IV, NULL);
    s32 defenseEV = GetMonData(mon, MON_DATA_DEF_EV, NULL);
    s32 speedIV = GetMonData(mon, MON_DATA_SPEED_IV, NULL);
    s32 speedEV = GetMonData(mon, MON_DATA_SPEED_EV, NULL);
    s32 spAttackIV = GetMonData(mon, MON_DATA_SPATK_IV, NULL);
    s32 spAttackEV = GetMonData(mon, MON_DATA_SPATK_EV, NULL);
    s32 spDefenseIV = GetMonData(mon, MON_DATA_SPDEF_IV, NULL);
    s32 spDefenseEV = GetMonData(mon, MON_DATA_SPDEF_EV, NULL);
    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    s32 level = GetLevelFromMonExp(mon);
    s32 newMaxHP;

    SetMonData(mon, MON_DATA_LEVEL, &level);

    if (species == SPECIES_SHEDINJA)
    {
        newMaxHP = 1;
    }
    else
    {
        s32 n = 2 * gBaseStats[species].baseHP + hpIV;
        newMaxHP = (((n + hpEV / 4) * level) / 100) + level + 10;
    }

    SetMonData(mon, MON_DATA_MAX_HP, &newMaxHP);

    CALC_STAT(baseAttack, attackIV, attackEV, 1, MON_DATA_ATK)
    CALC_STAT(baseDefense, defenseIV, defenseEV, 2, MON_DATA_DEF)
    CALC_STAT(baseSpeed, speedIV, speedEV, 3, MON_DATA_SPEED)
    CALC_STAT(baseSpAttack, spAttackIV, spAttackEV, 4, MON_DATA_SPATK)
    CALC_STAT(baseSpDefense, spDefenseIV, spDefenseEV, 5, MON_DATA_SPDEF)

    if (newMaxHP < currentHP)
        currentHP = newMaxHP;

    SetMonData(mon, MON_DATA_HP, &currentHP);
}
#endif

void ExpandBoxMon(const struct BoxPokemon *src, struct Pokemon *dest)
{
    u32 value = 0;
    dest->box = *src;
    SetMonData(dest, MON_DATA_STATUS, &value);
    SetMonData(dest, MON_DATA_HP, &value);
    SetMonData(dest, MON_DATA_MAX_HP, &value);
    value = 255;
    SetMonData(dest, MON_DATA_MAIL, &value);
    CalculateMonStats(dest);
}

u8 GetLevelFromMonExp(struct Pokemon *mon)
{
    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    u32 exp = GetMonData(mon, MON_DATA_EXP, NULL);
    s32 level = 1;

    while (level <= 100 && gExperienceTables[gBaseStats[species].growthRate][level] <= exp)
        level++;

    return level - 1;
}

u8 GetLevelFromBoxMonExp(struct BoxPokemon *boxMon)
{
    u16 species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    u32 exp = GetBoxMonData(boxMon, MON_DATA_EXP, NULL);
    s32 level = 1;

    while (level <= 100 && gExperienceTables[gBaseStats[species].growthRate][level] <= exp)
        level++;

    return level - 1;
}

u16 GiveMoveToMon(struct Pokemon *mon, u16 move)
{
    return GiveMoveToBoxMon(&mon->box, move);
}

u16 GiveMoveToBoxMon(struct BoxPokemon *boxMon, u16 move)
{
    s32 i;
    for (i = 0; i < 4; i++)
    {
        u16 existingMove = GetBoxMonData(boxMon, MON_DATA_MOVE1 + i, NULL);
        if (!existingMove)
        {
            SetBoxMonData(boxMon, MON_DATA_MOVE1 + i, &move);
            SetBoxMonData(boxMon, MON_DATA_PP1 + i, &gBattleMoves[move].pp);
            return move;
        }
        if (existingMove == move)
            return -2;
    }
    return -1;
}

u16 GiveMoveToBattleMon(struct BattlePokemon *mon, u16 move)
{
    s32 i;

    for (i = 0; i < 4; i++)
    {
        if (!mon->moves[i])
        {
            mon->moves[i] = move;
            mon->pp[i] = gBattleMoves[move].pp;
            return move;
        }
    }

    return -1;
}

void SetMonMoveSlot(struct Pokemon *mon, u16 move, u8 slot)
{
    SetMonData(mon, MON_DATA_MOVE1 + slot, &move);
    SetMonData(mon, MON_DATA_PP1 + slot, &gBattleMoves[move].pp);
}

void SetBattleMonMoveSlot(struct BattlePokemon *mon, u16 move, u8 slot)
{
    mon->moves[slot] = move;
    mon->pp[slot] = gBattleMoves[move].pp;
}

void GiveMonInitialMoveset(struct Pokemon *mon)
{
    GiveBoxMonInitialMoveset(&mon->box);
}

void GiveBoxMonInitialMoveset(struct BoxPokemon *boxMon)
{
    u16 species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    s32 level = GetLevelFromBoxMonExp(boxMon);
    s32 i;

    for (i = 0; gLevelUpLearnsets[species][i] != LEVEL_UP_END; i++)
    {
        u16 moveLevel;
        u16 move;

        moveLevel = (gLevelUpLearnsets[species][i] & 0xFF0000);

        if (moveLevel > (level << 16))
            break;

        move = (gLevelUpLearnsets[species][i] & 0x00FFFF);

        if (GiveMoveToBoxMon(boxMon, move) == (u16)-1)
            DeleteFirstMoveAndGiveMoveToBoxMon(boxMon, move);
    }
}

u16 MonTryLearningNewMove(struct Pokemon *mon, bool8 firstMove)
{
    u32 retVal = 0;
    u16 species = GetMonData(mon, MON_DATA_SPECIES, NULL);
    u8 level = GetMonData(mon, MON_DATA_LEVEL, NULL);

    // since you can learn more than one move per level
    // the game needs to know whether you decided to
    // learn it or keep the old set to avoid asking
    // you to learn the same move over and over again
    if (firstMove)
    {
        sLearningMoveTableID = 0;

        while ((gLevelUpLearnsets[species][sLearningMoveTableID] & 0xFF0000) != (level << 16))
        {
            sLearningMoveTableID++;
            if (gLevelUpLearnsets[species][sLearningMoveTableID] == LEVEL_UP_END)
                return 0;
        }
    }

    if ((gLevelUpLearnsets[species][sLearningMoveTableID] & 0xFF0000) == (level << 16))
    {
        gMoveToLearn = (gLevelUpLearnsets[species][sLearningMoveTableID] & 0x00FFFF);
        sLearningMoveTableID++;
        retVal = GiveMoveToMon(mon, gMoveToLearn);
    }

    return retVal;
}

void DeleteFirstMoveAndGiveMoveToMon(struct Pokemon *mon, u16 move)
{
    s32 i;
    u16 moves[4];
    u8 pp[4];
    u8 ppBonuses;

    for (i = 0; i < 3; i++)
    {
        moves[i] = GetMonData(mon, MON_DATA_MOVE2 + i, NULL);
        pp[i] = GetMonData(mon, MON_DATA_PP2 + i, NULL);
    }

    ppBonuses = GetMonData(mon, MON_DATA_PP_BONUSES, NULL);
    ppBonuses >>= 2;
    moves[3] = move;
    pp[3] = gBattleMoves[move].pp;

    for (i = 0; i < 4; i++)
    {
        SetMonData(mon, MON_DATA_MOVE1 + i, &moves[i]);
        SetMonData(mon, MON_DATA_PP1 + i, &pp[i]);
    }

    SetMonData(mon, MON_DATA_PP_BONUSES, &ppBonuses);
}

void DeleteFirstMoveAndGiveMoveToBoxMon(struct BoxPokemon *boxMon, u16 move)
{
    s32 i;
    u16 moves[4];
    u8 pp[4];
    u8 ppBonuses;

    for (i = 0; i < 3; i++)
    {
        moves[i] = GetBoxMonData(boxMon, MON_DATA_MOVE2 + i, NULL);
        pp[i] = GetBoxMonData(boxMon, MON_DATA_PP2 + i, NULL);
    }

    ppBonuses = GetBoxMonData(boxMon, MON_DATA_PP_BONUSES, NULL);
    ppBonuses >>= 2;
    moves[3] = move;
    pp[3] = gBattleMoves[move].pp;

    for (i = 0; i < 4; i++)
    {
        SetBoxMonData(boxMon, MON_DATA_MOVE1 + i, &moves[i]);
        SetBoxMonData(boxMon, MON_DATA_PP1 + i, &pp[i]);
    }

    SetBoxMonData(boxMon, MON_DATA_PP_BONUSES, &ppBonuses);
}
